/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.56.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AiOrdersUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiOrdersUpdateRequest{}

// AiOrdersUpdateRequest struct for AiOrdersUpdateRequest
type AiOrdersUpdateRequest struct {
	ProjectId int32 `json:"project_id"`
	Platform string `json:"platform"`
	// ISO 4217 code, e.g. EUR
	Currency string `json:"currency"`
	// First day of the window this push replaces
	From string `json:"from"`
	// Last day of the window; at most 400 days after from
	To string `json:"to"`
	Days []AiOrdersUpdateRequestDaysInner `json:"days"`
}

type _AiOrdersUpdateRequest AiOrdersUpdateRequest

// NewAiOrdersUpdateRequest instantiates a new AiOrdersUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiOrdersUpdateRequest(projectId int32, platform string, currency string, from string, to string, days []AiOrdersUpdateRequestDaysInner) *AiOrdersUpdateRequest {
	this := AiOrdersUpdateRequest{}
	this.ProjectId = projectId
	this.Platform = platform
	this.Currency = currency
	this.From = from
	this.To = to
	this.Days = days
	return &this
}

// NewAiOrdersUpdateRequestWithDefaults instantiates a new AiOrdersUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiOrdersUpdateRequestWithDefaults() *AiOrdersUpdateRequest {
	this := AiOrdersUpdateRequest{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *AiOrdersUpdateRequest) GetProjectId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *AiOrdersUpdateRequest) GetProjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *AiOrdersUpdateRequest) SetProjectId(v int32) {
	o.ProjectId = v
}

// GetPlatform returns the Platform field value
func (o *AiOrdersUpdateRequest) GetPlatform() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value
// and a boolean to check if the value has been set.
func (o *AiOrdersUpdateRequest) GetPlatformOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Platform, true
}

// SetPlatform sets field value
func (o *AiOrdersUpdateRequest) SetPlatform(v string) {
	o.Platform = v
}

// GetCurrency returns the Currency field value
func (o *AiOrdersUpdateRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *AiOrdersUpdateRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *AiOrdersUpdateRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetFrom returns the From field value
func (o *AiOrdersUpdateRequest) GetFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *AiOrdersUpdateRequest) GetFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *AiOrdersUpdateRequest) SetFrom(v string) {
	o.From = v
}

// GetTo returns the To field value
func (o *AiOrdersUpdateRequest) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *AiOrdersUpdateRequest) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *AiOrdersUpdateRequest) SetTo(v string) {
	o.To = v
}

// GetDays returns the Days field value
func (o *AiOrdersUpdateRequest) GetDays() []AiOrdersUpdateRequestDaysInner {
	if o == nil {
		var ret []AiOrdersUpdateRequestDaysInner
		return ret
	}

	return o.Days
}

// GetDaysOk returns a tuple with the Days field value
// and a boolean to check if the value has been set.
func (o *AiOrdersUpdateRequest) GetDaysOk() ([]AiOrdersUpdateRequestDaysInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Days, true
}

// SetDays sets field value
func (o *AiOrdersUpdateRequest) SetDays(v []AiOrdersUpdateRequestDaysInner) {
	o.Days = v
}

func (o AiOrdersUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiOrdersUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["platform"] = o.Platform
	toSerialize["currency"] = o.Currency
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	toSerialize["days"] = o.Days
	return toSerialize, nil
}

func (o *AiOrdersUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"platform",
		"currency",
		"from",
		"to",
		"days",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAiOrdersUpdateRequest := _AiOrdersUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAiOrdersUpdateRequest)

	if err != nil {
		return err
	}

	*o = AiOrdersUpdateRequest(varAiOrdersUpdateRequest)

	return err
}

type NullableAiOrdersUpdateRequest struct {
	value *AiOrdersUpdateRequest
	isSet bool
}

func (v NullableAiOrdersUpdateRequest) Get() *AiOrdersUpdateRequest {
	return v.value
}

func (v *NullableAiOrdersUpdateRequest) Set(val *AiOrdersUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAiOrdersUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAiOrdersUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiOrdersUpdateRequest(val *AiOrdersUpdateRequest) *NullableAiOrdersUpdateRequest {
	return &NullableAiOrdersUpdateRequest{value: val, isSet: true}
}

func (v NullableAiOrdersUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiOrdersUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


