/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.56.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
)

// checks if the PromptsCreateResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromptsCreateResponseDataInner{}

// PromptsCreateResponseDataInner struct for PromptsCreateResponseDataInner
type PromptsCreateResponseDataInner struct {
	Id *int32 `json:"id,omitempty"`
	RawInput *string `json:"raw_input,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewPromptsCreateResponseDataInner instantiates a new PromptsCreateResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromptsCreateResponseDataInner() *PromptsCreateResponseDataInner {
	this := PromptsCreateResponseDataInner{}
	return &this
}

// NewPromptsCreateResponseDataInnerWithDefaults instantiates a new PromptsCreateResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromptsCreateResponseDataInnerWithDefaults() *PromptsCreateResponseDataInner {
	this := PromptsCreateResponseDataInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PromptsCreateResponseDataInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromptsCreateResponseDataInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PromptsCreateResponseDataInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *PromptsCreateResponseDataInner) SetId(v int32) {
	o.Id = &v
}

// GetRawInput returns the RawInput field value if set, zero value otherwise.
func (o *PromptsCreateResponseDataInner) GetRawInput() string {
	if o == nil || IsNil(o.RawInput) {
		var ret string
		return ret
	}
	return *o.RawInput
}

// GetRawInputOk returns a tuple with the RawInput field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromptsCreateResponseDataInner) GetRawInputOk() (*string, bool) {
	if o == nil || IsNil(o.RawInput) {
		return nil, false
	}
	return o.RawInput, true
}

// HasRawInput returns a boolean if a field has been set.
func (o *PromptsCreateResponseDataInner) HasRawInput() bool {
	if o != nil && !IsNil(o.RawInput) {
		return true
	}

	return false
}

// SetRawInput gets a reference to the given string and assigns it to the RawInput field.
func (o *PromptsCreateResponseDataInner) SetRawInput(v string) {
	o.RawInput = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PromptsCreateResponseDataInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromptsCreateResponseDataInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PromptsCreateResponseDataInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PromptsCreateResponseDataInner) SetStatus(v string) {
	o.Status = &v
}

func (o PromptsCreateResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromptsCreateResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.RawInput) {
		toSerialize["raw_input"] = o.RawInput
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullablePromptsCreateResponseDataInner struct {
	value *PromptsCreateResponseDataInner
	isSet bool
}

func (v NullablePromptsCreateResponseDataInner) Get() *PromptsCreateResponseDataInner {
	return v.value
}

func (v *NullablePromptsCreateResponseDataInner) Set(val *PromptsCreateResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePromptsCreateResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePromptsCreateResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromptsCreateResponseDataInner(val *PromptsCreateResponseDataInner) *NullablePromptsCreateResponseDataInner {
	return &NullablePromptsCreateResponseDataInner{value: val, isSet: true}
}

func (v NullablePromptsCreateResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromptsCreateResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


