/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.22.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCompetitorRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCompetitorRequest{}

// CreateCompetitorRequest struct for CreateCompetitorRequest
type CreateCompetitorRequest struct {
	ProjectId int32 `json:"project_id"`
	BrandName string `json:"brand_name"`
	// URL is accepted and normalised to host (e.g. https://www.openai.com → openai.com)
	Domain string `json:"domain"`
	MatchingNames []string `json:"matching_names,omitempty"`
}

type _CreateCompetitorRequest CreateCompetitorRequest

// NewCreateCompetitorRequest instantiates a new CreateCompetitorRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCompetitorRequest(projectId int32, brandName string, domain string) *CreateCompetitorRequest {
	this := CreateCompetitorRequest{}
	this.ProjectId = projectId
	this.BrandName = brandName
	this.Domain = domain
	return &this
}

// NewCreateCompetitorRequestWithDefaults instantiates a new CreateCompetitorRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCompetitorRequestWithDefaults() *CreateCompetitorRequest {
	this := CreateCompetitorRequest{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *CreateCompetitorRequest) GetProjectId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *CreateCompetitorRequest) GetProjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *CreateCompetitorRequest) SetProjectId(v int32) {
	o.ProjectId = v
}

// GetBrandName returns the BrandName field value
func (o *CreateCompetitorRequest) GetBrandName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BrandName
}

// GetBrandNameOk returns a tuple with the BrandName field value
// and a boolean to check if the value has been set.
func (o *CreateCompetitorRequest) GetBrandNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BrandName, true
}

// SetBrandName sets field value
func (o *CreateCompetitorRequest) SetBrandName(v string) {
	o.BrandName = v
}

// GetDomain returns the Domain field value
func (o *CreateCompetitorRequest) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *CreateCompetitorRequest) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *CreateCompetitorRequest) SetDomain(v string) {
	o.Domain = v
}

// GetMatchingNames returns the MatchingNames field value if set, zero value otherwise.
func (o *CreateCompetitorRequest) GetMatchingNames() []string {
	if o == nil || IsNil(o.MatchingNames) {
		var ret []string
		return ret
	}
	return o.MatchingNames
}

// GetMatchingNamesOk returns a tuple with the MatchingNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCompetitorRequest) GetMatchingNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.MatchingNames) {
		return nil, false
	}
	return o.MatchingNames, true
}

// HasMatchingNames returns a boolean if a field has been set.
func (o *CreateCompetitorRequest) HasMatchingNames() bool {
	if o != nil && !IsNil(o.MatchingNames) {
		return true
	}

	return false
}

// SetMatchingNames gets a reference to the given []string and assigns it to the MatchingNames field.
func (o *CreateCompetitorRequest) SetMatchingNames(v []string) {
	o.MatchingNames = v
}

func (o CreateCompetitorRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCompetitorRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["brand_name"] = o.BrandName
	toSerialize["domain"] = o.Domain
	if !IsNil(o.MatchingNames) {
		toSerialize["matching_names"] = o.MatchingNames
	}
	return toSerialize, nil
}

func (o *CreateCompetitorRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"brand_name",
		"domain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCompetitorRequest := _CreateCompetitorRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCompetitorRequest)

	if err != nil {
		return err
	}

	*o = CreateCompetitorRequest(varCreateCompetitorRequest)

	return err
}

type NullableCreateCompetitorRequest struct {
	value *CreateCompetitorRequest
	isSet bool
}

func (v NullableCreateCompetitorRequest) Get() *CreateCompetitorRequest {
	return v.value
}

func (v *NullableCreateCompetitorRequest) Set(val *CreateCompetitorRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCompetitorRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCompetitorRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCompetitorRequest(val *CreateCompetitorRequest) *NullableCreateCompetitorRequest {
	return &NullableCreateCompetitorRequest{value: val, isSet: true}
}

func (v NullableCreateCompetitorRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCompetitorRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


