/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.57.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
)

// checks if the GeoAlertEventsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeoAlertEventsInner{}

// GeoAlertEventsInner struct for GeoAlertEventsInner
type GeoAlertEventsInner struct {
	Kind *string `json:"kind,omitempty"`
	CheckKey NullableString `json:"check_key,omitempty"`
	SubjectKey NullableString `json:"subject_key,omitempty"`
	Severity *string `json:"severity,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewGeoAlertEventsInner instantiates a new GeoAlertEventsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeoAlertEventsInner() *GeoAlertEventsInner {
	this := GeoAlertEventsInner{}
	return &this
}

// NewGeoAlertEventsInnerWithDefaults instantiates a new GeoAlertEventsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeoAlertEventsInnerWithDefaults() *GeoAlertEventsInner {
	this := GeoAlertEventsInner{}
	return &this
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *GeoAlertEventsInner) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAlertEventsInner) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *GeoAlertEventsInner) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *GeoAlertEventsInner) SetKind(v string) {
	o.Kind = &v
}

// GetCheckKey returns the CheckKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GeoAlertEventsInner) GetCheckKey() string {
	if o == nil || IsNil(o.CheckKey.Get()) {
		var ret string
		return ret
	}
	return *o.CheckKey.Get()
}

// GetCheckKeyOk returns a tuple with the CheckKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GeoAlertEventsInner) GetCheckKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CheckKey.Get(), o.CheckKey.IsSet()
}

// HasCheckKey returns a boolean if a field has been set.
func (o *GeoAlertEventsInner) HasCheckKey() bool {
	if o != nil && o.CheckKey.IsSet() {
		return true
	}

	return false
}

// SetCheckKey gets a reference to the given NullableString and assigns it to the CheckKey field.
func (o *GeoAlertEventsInner) SetCheckKey(v string) {
	o.CheckKey.Set(&v)
}
// SetCheckKeyNil sets the value for CheckKey to be an explicit nil
func (o *GeoAlertEventsInner) SetCheckKeyNil() {
	o.CheckKey.Set(nil)
}

// UnsetCheckKey ensures that no value is present for CheckKey, not even an explicit nil
func (o *GeoAlertEventsInner) UnsetCheckKey() {
	o.CheckKey.Unset()
}

// GetSubjectKey returns the SubjectKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GeoAlertEventsInner) GetSubjectKey() string {
	if o == nil || IsNil(o.SubjectKey.Get()) {
		var ret string
		return ret
	}
	return *o.SubjectKey.Get()
}

// GetSubjectKeyOk returns a tuple with the SubjectKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GeoAlertEventsInner) GetSubjectKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubjectKey.Get(), o.SubjectKey.IsSet()
}

// HasSubjectKey returns a boolean if a field has been set.
func (o *GeoAlertEventsInner) HasSubjectKey() bool {
	if o != nil && o.SubjectKey.IsSet() {
		return true
	}

	return false
}

// SetSubjectKey gets a reference to the given NullableString and assigns it to the SubjectKey field.
func (o *GeoAlertEventsInner) SetSubjectKey(v string) {
	o.SubjectKey.Set(&v)
}
// SetSubjectKeyNil sets the value for SubjectKey to be an explicit nil
func (o *GeoAlertEventsInner) SetSubjectKeyNil() {
	o.SubjectKey.Set(nil)
}

// UnsetSubjectKey ensures that no value is present for SubjectKey, not even an explicit nil
func (o *GeoAlertEventsInner) UnsetSubjectKey() {
	o.SubjectKey.Unset()
}

// GetSeverity returns the Severity field value if set, zero value otherwise.
func (o *GeoAlertEventsInner) GetSeverity() string {
	if o == nil || IsNil(o.Severity) {
		var ret string
		return ret
	}
	return *o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAlertEventsInner) GetSeverityOk() (*string, bool) {
	if o == nil || IsNil(o.Severity) {
		return nil, false
	}
	return o.Severity, true
}

// HasSeverity returns a boolean if a field has been set.
func (o *GeoAlertEventsInner) HasSeverity() bool {
	if o != nil && !IsNil(o.Severity) {
		return true
	}

	return false
}

// SetSeverity gets a reference to the given string and assigns it to the Severity field.
func (o *GeoAlertEventsInner) SetSeverity(v string) {
	o.Severity = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GeoAlertEventsInner) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAlertEventsInner) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GeoAlertEventsInner) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GeoAlertEventsInner) SetMessage(v string) {
	o.Message = &v
}

func (o GeoAlertEventsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeoAlertEventsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if o.CheckKey.IsSet() {
		toSerialize["check_key"] = o.CheckKey.Get()
	}
	if o.SubjectKey.IsSet() {
		toSerialize["subject_key"] = o.SubjectKey.Get()
	}
	if !IsNil(o.Severity) {
		toSerialize["severity"] = o.Severity
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableGeoAlertEventsInner struct {
	value *GeoAlertEventsInner
	isSet bool
}

func (v NullableGeoAlertEventsInner) Get() *GeoAlertEventsInner {
	return v.value
}

func (v *NullableGeoAlertEventsInner) Set(val *GeoAlertEventsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGeoAlertEventsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGeoAlertEventsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeoAlertEventsInner(val *GeoAlertEventsInner) *NullableGeoAlertEventsInner {
	return &NullableGeoAlertEventsInner{value: val, isSet: true}
}

func (v NullableGeoAlertEventsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeoAlertEventsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


