/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.50.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateProjectDraftRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProjectDraftRequest{}

// CreateProjectDraftRequest struct for CreateProjectDraftRequest
type CreateProjectDraftRequest struct {
	// Public HTTP(S) URL with a DNS hostname or public IP address. Credentials, private and special IP addresses, localhost and internal hostnames are rejected.
	WebsiteUrl string `json:"website_url"`
	MainCountry string `json:"main_country"`
	MainLanguage string `json:"main_language"`
	UseSubdomain *bool `json:"use_subdomain,omitempty"`
	Suggest *bool `json:"suggest,omitempty"`
	ExecutePromptsImmediately *bool `json:"execute_prompts_immediately,omitempty"`
}

type _CreateProjectDraftRequest CreateProjectDraftRequest

// NewCreateProjectDraftRequest instantiates a new CreateProjectDraftRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProjectDraftRequest(websiteUrl string, mainCountry string, mainLanguage string) *CreateProjectDraftRequest {
	this := CreateProjectDraftRequest{}
	this.WebsiteUrl = websiteUrl
	this.MainCountry = mainCountry
	this.MainLanguage = mainLanguage
	var useSubdomain bool = false
	this.UseSubdomain = &useSubdomain
	var suggest bool = true
	this.Suggest = &suggest
	var executePromptsImmediately bool = true
	this.ExecutePromptsImmediately = &executePromptsImmediately
	return &this
}

// NewCreateProjectDraftRequestWithDefaults instantiates a new CreateProjectDraftRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProjectDraftRequestWithDefaults() *CreateProjectDraftRequest {
	this := CreateProjectDraftRequest{}
	var useSubdomain bool = false
	this.UseSubdomain = &useSubdomain
	var suggest bool = true
	this.Suggest = &suggest
	var executePromptsImmediately bool = true
	this.ExecutePromptsImmediately = &executePromptsImmediately
	return &this
}

// GetWebsiteUrl returns the WebsiteUrl field value
func (o *CreateProjectDraftRequest) GetWebsiteUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WebsiteUrl
}

// GetWebsiteUrlOk returns a tuple with the WebsiteUrl field value
// and a boolean to check if the value has been set.
func (o *CreateProjectDraftRequest) GetWebsiteUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WebsiteUrl, true
}

// SetWebsiteUrl sets field value
func (o *CreateProjectDraftRequest) SetWebsiteUrl(v string) {
	o.WebsiteUrl = v
}

// GetMainCountry returns the MainCountry field value
func (o *CreateProjectDraftRequest) GetMainCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MainCountry
}

// GetMainCountryOk returns a tuple with the MainCountry field value
// and a boolean to check if the value has been set.
func (o *CreateProjectDraftRequest) GetMainCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MainCountry, true
}

// SetMainCountry sets field value
func (o *CreateProjectDraftRequest) SetMainCountry(v string) {
	o.MainCountry = v
}

// GetMainLanguage returns the MainLanguage field value
func (o *CreateProjectDraftRequest) GetMainLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MainLanguage
}

// GetMainLanguageOk returns a tuple with the MainLanguage field value
// and a boolean to check if the value has been set.
func (o *CreateProjectDraftRequest) GetMainLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MainLanguage, true
}

// SetMainLanguage sets field value
func (o *CreateProjectDraftRequest) SetMainLanguage(v string) {
	o.MainLanguage = v
}

// GetUseSubdomain returns the UseSubdomain field value if set, zero value otherwise.
func (o *CreateProjectDraftRequest) GetUseSubdomain() bool {
	if o == nil || IsNil(o.UseSubdomain) {
		var ret bool
		return ret
	}
	return *o.UseSubdomain
}

// GetUseSubdomainOk returns a tuple with the UseSubdomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectDraftRequest) GetUseSubdomainOk() (*bool, bool) {
	if o == nil || IsNil(o.UseSubdomain) {
		return nil, false
	}
	return o.UseSubdomain, true
}

// HasUseSubdomain returns a boolean if a field has been set.
func (o *CreateProjectDraftRequest) HasUseSubdomain() bool {
	if o != nil && !IsNil(o.UseSubdomain) {
		return true
	}

	return false
}

// SetUseSubdomain gets a reference to the given bool and assigns it to the UseSubdomain field.
func (o *CreateProjectDraftRequest) SetUseSubdomain(v bool) {
	o.UseSubdomain = &v
}

// GetSuggest returns the Suggest field value if set, zero value otherwise.
func (o *CreateProjectDraftRequest) GetSuggest() bool {
	if o == nil || IsNil(o.Suggest) {
		var ret bool
		return ret
	}
	return *o.Suggest
}

// GetSuggestOk returns a tuple with the Suggest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectDraftRequest) GetSuggestOk() (*bool, bool) {
	if o == nil || IsNil(o.Suggest) {
		return nil, false
	}
	return o.Suggest, true
}

// HasSuggest returns a boolean if a field has been set.
func (o *CreateProjectDraftRequest) HasSuggest() bool {
	if o != nil && !IsNil(o.Suggest) {
		return true
	}

	return false
}

// SetSuggest gets a reference to the given bool and assigns it to the Suggest field.
func (o *CreateProjectDraftRequest) SetSuggest(v bool) {
	o.Suggest = &v
}

// GetExecutePromptsImmediately returns the ExecutePromptsImmediately field value if set, zero value otherwise.
func (o *CreateProjectDraftRequest) GetExecutePromptsImmediately() bool {
	if o == nil || IsNil(o.ExecutePromptsImmediately) {
		var ret bool
		return ret
	}
	return *o.ExecutePromptsImmediately
}

// GetExecutePromptsImmediatelyOk returns a tuple with the ExecutePromptsImmediately field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProjectDraftRequest) GetExecutePromptsImmediatelyOk() (*bool, bool) {
	if o == nil || IsNil(o.ExecutePromptsImmediately) {
		return nil, false
	}
	return o.ExecutePromptsImmediately, true
}

// HasExecutePromptsImmediately returns a boolean if a field has been set.
func (o *CreateProjectDraftRequest) HasExecutePromptsImmediately() bool {
	if o != nil && !IsNil(o.ExecutePromptsImmediately) {
		return true
	}

	return false
}

// SetExecutePromptsImmediately gets a reference to the given bool and assigns it to the ExecutePromptsImmediately field.
func (o *CreateProjectDraftRequest) SetExecutePromptsImmediately(v bool) {
	o.ExecutePromptsImmediately = &v
}

func (o CreateProjectDraftRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProjectDraftRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["website_url"] = o.WebsiteUrl
	toSerialize["main_country"] = o.MainCountry
	toSerialize["main_language"] = o.MainLanguage
	if !IsNil(o.UseSubdomain) {
		toSerialize["use_subdomain"] = o.UseSubdomain
	}
	if !IsNil(o.Suggest) {
		toSerialize["suggest"] = o.Suggest
	}
	if !IsNil(o.ExecutePromptsImmediately) {
		toSerialize["execute_prompts_immediately"] = o.ExecutePromptsImmediately
	}
	return toSerialize, nil
}

func (o *CreateProjectDraftRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"website_url",
		"main_country",
		"main_language",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateProjectDraftRequest := _CreateProjectDraftRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateProjectDraftRequest)

	if err != nil {
		return err
	}

	*o = CreateProjectDraftRequest(varCreateProjectDraftRequest)

	return err
}

type NullableCreateProjectDraftRequest struct {
	value *CreateProjectDraftRequest
	isSet bool
}

func (v NullableCreateProjectDraftRequest) Get() *CreateProjectDraftRequest {
	return v.value
}

func (v *NullableCreateProjectDraftRequest) Set(val *CreateProjectDraftRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProjectDraftRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProjectDraftRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProjectDraftRequest(val *CreateProjectDraftRequest) *NullableCreateProjectDraftRequest {
	return &NullableCreateProjectDraftRequest{value: val, isSet: true}
}

func (v NullableCreateProjectDraftRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProjectDraftRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


