/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.56.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"time"
)

// checks if the GeoAuditRunDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeoAuditRunDetail{}

// GeoAuditRunDetail struct for GeoAuditRunDetail
type GeoAuditRunDetail struct {
	// Run number within the audit, starting at 1
	Sequence *int32 `json:"sequence,omitempty"`
	Status *string `json:"status,omitempty"`
	Trigger *string `json:"trigger,omitempty"`
	Score NullableFloat32 `json:"score,omitempty"`
	Grade NullableString `json:"grade,omitempty"`
	// Score change against the previous completed run
	ScoreDelta NullableFloat32 `json:"score_delta,omitempty"`
	// False when the checks or the audit settings changed since the previous run, so a diff may reflect that change
	ComparableToPrevious *bool `json:"comparable_to_previous,omitempty"`
	NewIssues *int32 `json:"new_issues,omitempty"`
	FixedIssues *int32 `json:"fixed_issues,omitempty"`
	RegressedIssues *int32 `json:"regressed_issues,omitempty"`
	Error NullableString `json:"error,omitempty"`
	EngineVersion NullableString `json:"engine_version,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	FinishedAt NullableTime `json:"finished_at,omitempty"`
	AppUrl *string `json:"app_url,omitempty"`
	ProjectId *int32 `json:"project_id,omitempty"`
	Metrics *map[string]float32 `json:"metrics,omitempty"`
	// The full report of the run, in the shape of the matching technical GEO report type
	ResultData map[string]interface{} `json:"result_data,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
}

// NewGeoAuditRunDetail instantiates a new GeoAuditRunDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeoAuditRunDetail() *GeoAuditRunDetail {
	this := GeoAuditRunDetail{}
	return &this
}

// NewGeoAuditRunDetailWithDefaults instantiates a new GeoAuditRunDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeoAuditRunDetailWithDefaults() *GeoAuditRunDetail {
	this := GeoAuditRunDetail{}
	return &this
}

// GetSequence returns the Sequence field value if set, zero value otherwise.
func (o *GeoAuditRunDetail) GetSequence() int32 {
	if o == nil || IsNil(o.Sequence) {
		var ret int32
		return ret
	}
	return *o.Sequence
}

// GetSequenceOk returns a tuple with the Sequence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditRunDetail) GetSequenceOk() (*int32, bool) {
	if o == nil || IsNil(o.Sequence) {
		return nil, false
	}
	return o.Sequence, true
}

// HasSequence returns a boolean if a field has been set.
func (o *GeoAuditRunDetail) HasSequence() bool {
	if o != nil && !IsNil(o.Sequence) {
		return true
	}

	return false
}

// SetSequence gets a reference to the given int32 and assigns it to the Sequence field.
func (o *GeoAuditRunDetail) SetSequence(v int32) {
	o.Sequence = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GeoAuditRunDetail) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditRunDetail) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GeoAuditRunDetail) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GeoAuditRunDetail) SetStatus(v string) {
	o.Status = &v
}

// GetTrigger returns the Trigger field value if set, zero value otherwise.
func (o *GeoAuditRunDetail) GetTrigger() string {
	if o == nil || IsNil(o.Trigger) {
		var ret string
		return ret
	}
	return *o.Trigger
}

// GetTriggerOk returns a tuple with the Trigger field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditRunDetail) GetTriggerOk() (*string, bool) {
	if o == nil || IsNil(o.Trigger) {
		return nil, false
	}
	return o.Trigger, true
}

// HasTrigger returns a boolean if a field has been set.
func (o *GeoAuditRunDetail) HasTrigger() bool {
	if o != nil && !IsNil(o.Trigger) {
		return true
	}

	return false
}

// SetTrigger gets a reference to the given string and assigns it to the Trigger field.
func (o *GeoAuditRunDetail) SetTrigger(v string) {
	o.Trigger = &v
}

// GetScore returns the Score field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GeoAuditRunDetail) GetScore() float32 {
	if o == nil || IsNil(o.Score.Get()) {
		var ret float32
		return ret
	}
	return *o.Score.Get()
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GeoAuditRunDetail) GetScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Score.Get(), o.Score.IsSet()
}

// HasScore returns a boolean if a field has been set.
func (o *GeoAuditRunDetail) HasScore() bool {
	if o != nil && o.Score.IsSet() {
		return true
	}

	return false
}

// SetScore gets a reference to the given NullableFloat32 and assigns it to the Score field.
func (o *GeoAuditRunDetail) SetScore(v float32) {
	o.Score.Set(&v)
}
// SetScoreNil sets the value for Score to be an explicit nil
func (o *GeoAuditRunDetail) SetScoreNil() {
	o.Score.Set(nil)
}

// UnsetScore ensures that no value is present for Score, not even an explicit nil
func (o *GeoAuditRunDetail) UnsetScore() {
	o.Score.Unset()
}

// GetGrade returns the Grade field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GeoAuditRunDetail) GetGrade() string {
	if o == nil || IsNil(o.Grade.Get()) {
		var ret string
		return ret
	}
	return *o.Grade.Get()
}

// GetGradeOk returns a tuple with the Grade field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GeoAuditRunDetail) GetGradeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Grade.Get(), o.Grade.IsSet()
}

// HasGrade returns a boolean if a field has been set.
func (o *GeoAuditRunDetail) HasGrade() bool {
	if o != nil && o.Grade.IsSet() {
		return true
	}

	return false
}

// SetGrade gets a reference to the given NullableString and assigns it to the Grade field.
func (o *GeoAuditRunDetail) SetGrade(v string) {
	o.Grade.Set(&v)
}
// SetGradeNil sets the value for Grade to be an explicit nil
func (o *GeoAuditRunDetail) SetGradeNil() {
	o.Grade.Set(nil)
}

// UnsetGrade ensures that no value is present for Grade, not even an explicit nil
func (o *GeoAuditRunDetail) UnsetGrade() {
	o.Grade.Unset()
}

// GetScoreDelta returns the ScoreDelta field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GeoAuditRunDetail) GetScoreDelta() float32 {
	if o == nil || IsNil(o.ScoreDelta.Get()) {
		var ret float32
		return ret
	}
	return *o.ScoreDelta.Get()
}

// GetScoreDeltaOk returns a tuple with the ScoreDelta field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GeoAuditRunDetail) GetScoreDeltaOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ScoreDelta.Get(), o.ScoreDelta.IsSet()
}

// HasScoreDelta returns a boolean if a field has been set.
func (o *GeoAuditRunDetail) HasScoreDelta() bool {
	if o != nil && o.ScoreDelta.IsSet() {
		return true
	}

	return false
}

// SetScoreDelta gets a reference to the given NullableFloat32 and assigns it to the ScoreDelta field.
func (o *GeoAuditRunDetail) SetScoreDelta(v float32) {
	o.ScoreDelta.Set(&v)
}
// SetScoreDeltaNil sets the value for ScoreDelta to be an explicit nil
func (o *GeoAuditRunDetail) SetScoreDeltaNil() {
	o.ScoreDelta.Set(nil)
}

// UnsetScoreDelta ensures that no value is present for ScoreDelta, not even an explicit nil
func (o *GeoAuditRunDetail) UnsetScoreDelta() {
	o.ScoreDelta.Unset()
}

// GetComparableToPrevious returns the ComparableToPrevious field value if set, zero value otherwise.
func (o *GeoAuditRunDetail) GetComparableToPrevious() bool {
	if o == nil || IsNil(o.ComparableToPrevious) {
		var ret bool
		return ret
	}
	return *o.ComparableToPrevious
}

// GetComparableToPreviousOk returns a tuple with the ComparableToPrevious field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditRunDetail) GetComparableToPreviousOk() (*bool, bool) {
	if o == nil || IsNil(o.ComparableToPrevious) {
		return nil, false
	}
	return o.ComparableToPrevious, true
}

// HasComparableToPrevious returns a boolean if a field has been set.
func (o *GeoAuditRunDetail) HasComparableToPrevious() bool {
	if o != nil && !IsNil(o.ComparableToPrevious) {
		return true
	}

	return false
}

// SetComparableToPrevious gets a reference to the given bool and assigns it to the ComparableToPrevious field.
func (o *GeoAuditRunDetail) SetComparableToPrevious(v bool) {
	o.ComparableToPrevious = &v
}

// GetNewIssues returns the NewIssues field value if set, zero value otherwise.
func (o *GeoAuditRunDetail) GetNewIssues() int32 {
	if o == nil || IsNil(o.NewIssues) {
		var ret int32
		return ret
	}
	return *o.NewIssues
}

// GetNewIssuesOk returns a tuple with the NewIssues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditRunDetail) GetNewIssuesOk() (*int32, bool) {
	if o == nil || IsNil(o.NewIssues) {
		return nil, false
	}
	return o.NewIssues, true
}

// HasNewIssues returns a boolean if a field has been set.
func (o *GeoAuditRunDetail) HasNewIssues() bool {
	if o != nil && !IsNil(o.NewIssues) {
		return true
	}

	return false
}

// SetNewIssues gets a reference to the given int32 and assigns it to the NewIssues field.
func (o *GeoAuditRunDetail) SetNewIssues(v int32) {
	o.NewIssues = &v
}

// GetFixedIssues returns the FixedIssues field value if set, zero value otherwise.
func (o *GeoAuditRunDetail) GetFixedIssues() int32 {
	if o == nil || IsNil(o.FixedIssues) {
		var ret int32
		return ret
	}
	return *o.FixedIssues
}

// GetFixedIssuesOk returns a tuple with the FixedIssues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditRunDetail) GetFixedIssuesOk() (*int32, bool) {
	if o == nil || IsNil(o.FixedIssues) {
		return nil, false
	}
	return o.FixedIssues, true
}

// HasFixedIssues returns a boolean if a field has been set.
func (o *GeoAuditRunDetail) HasFixedIssues() bool {
	if o != nil && !IsNil(o.FixedIssues) {
		return true
	}

	return false
}

// SetFixedIssues gets a reference to the given int32 and assigns it to the FixedIssues field.
func (o *GeoAuditRunDetail) SetFixedIssues(v int32) {
	o.FixedIssues = &v
}

// GetRegressedIssues returns the RegressedIssues field value if set, zero value otherwise.
func (o *GeoAuditRunDetail) GetRegressedIssues() int32 {
	if o == nil || IsNil(o.RegressedIssues) {
		var ret int32
		return ret
	}
	return *o.RegressedIssues
}

// GetRegressedIssuesOk returns a tuple with the RegressedIssues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditRunDetail) GetRegressedIssuesOk() (*int32, bool) {
	if o == nil || IsNil(o.RegressedIssues) {
		return nil, false
	}
	return o.RegressedIssues, true
}

// HasRegressedIssues returns a boolean if a field has been set.
func (o *GeoAuditRunDetail) HasRegressedIssues() bool {
	if o != nil && !IsNil(o.RegressedIssues) {
		return true
	}

	return false
}

// SetRegressedIssues gets a reference to the given int32 and assigns it to the RegressedIssues field.
func (o *GeoAuditRunDetail) SetRegressedIssues(v int32) {
	o.RegressedIssues = &v
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GeoAuditRunDetail) GetError() string {
	if o == nil || IsNil(o.Error.Get()) {
		var ret string
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GeoAuditRunDetail) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *GeoAuditRunDetail) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableString and assigns it to the Error field.
func (o *GeoAuditRunDetail) SetError(v string) {
	o.Error.Set(&v)
}
// SetErrorNil sets the value for Error to be an explicit nil
func (o *GeoAuditRunDetail) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *GeoAuditRunDetail) UnsetError() {
	o.Error.Unset()
}

// GetEngineVersion returns the EngineVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GeoAuditRunDetail) GetEngineVersion() string {
	if o == nil || IsNil(o.EngineVersion.Get()) {
		var ret string
		return ret
	}
	return *o.EngineVersion.Get()
}

// GetEngineVersionOk returns a tuple with the EngineVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GeoAuditRunDetail) GetEngineVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EngineVersion.Get(), o.EngineVersion.IsSet()
}

// HasEngineVersion returns a boolean if a field has been set.
func (o *GeoAuditRunDetail) HasEngineVersion() bool {
	if o != nil && o.EngineVersion.IsSet() {
		return true
	}

	return false
}

// SetEngineVersion gets a reference to the given NullableString and assigns it to the EngineVersion field.
func (o *GeoAuditRunDetail) SetEngineVersion(v string) {
	o.EngineVersion.Set(&v)
}
// SetEngineVersionNil sets the value for EngineVersion to be an explicit nil
func (o *GeoAuditRunDetail) SetEngineVersionNil() {
	o.EngineVersion.Set(nil)
}

// UnsetEngineVersion ensures that no value is present for EngineVersion, not even an explicit nil
func (o *GeoAuditRunDetail) UnsetEngineVersion() {
	o.EngineVersion.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GeoAuditRunDetail) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditRunDetail) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GeoAuditRunDetail) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *GeoAuditRunDetail) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetFinishedAt returns the FinishedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GeoAuditRunDetail) GetFinishedAt() time.Time {
	if o == nil || IsNil(o.FinishedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.FinishedAt.Get()
}

// GetFinishedAtOk returns a tuple with the FinishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GeoAuditRunDetail) GetFinishedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.FinishedAt.Get(), o.FinishedAt.IsSet()
}

// HasFinishedAt returns a boolean if a field has been set.
func (o *GeoAuditRunDetail) HasFinishedAt() bool {
	if o != nil && o.FinishedAt.IsSet() {
		return true
	}

	return false
}

// SetFinishedAt gets a reference to the given NullableTime and assigns it to the FinishedAt field.
func (o *GeoAuditRunDetail) SetFinishedAt(v time.Time) {
	o.FinishedAt.Set(&v)
}
// SetFinishedAtNil sets the value for FinishedAt to be an explicit nil
func (o *GeoAuditRunDetail) SetFinishedAtNil() {
	o.FinishedAt.Set(nil)
}

// UnsetFinishedAt ensures that no value is present for FinishedAt, not even an explicit nil
func (o *GeoAuditRunDetail) UnsetFinishedAt() {
	o.FinishedAt.Unset()
}

// GetAppUrl returns the AppUrl field value if set, zero value otherwise.
func (o *GeoAuditRunDetail) GetAppUrl() string {
	if o == nil || IsNil(o.AppUrl) {
		var ret string
		return ret
	}
	return *o.AppUrl
}

// GetAppUrlOk returns a tuple with the AppUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditRunDetail) GetAppUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AppUrl) {
		return nil, false
	}
	return o.AppUrl, true
}

// HasAppUrl returns a boolean if a field has been set.
func (o *GeoAuditRunDetail) HasAppUrl() bool {
	if o != nil && !IsNil(o.AppUrl) {
		return true
	}

	return false
}

// SetAppUrl gets a reference to the given string and assigns it to the AppUrl field.
func (o *GeoAuditRunDetail) SetAppUrl(v string) {
	o.AppUrl = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *GeoAuditRunDetail) GetProjectId() int32 {
	if o == nil || IsNil(o.ProjectId) {
		var ret int32
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditRunDetail) GetProjectIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *GeoAuditRunDetail) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given int32 and assigns it to the ProjectId field.
func (o *GeoAuditRunDetail) SetProjectId(v int32) {
	o.ProjectId = &v
}

// GetMetrics returns the Metrics field value if set, zero value otherwise.
func (o *GeoAuditRunDetail) GetMetrics() map[string]float32 {
	if o == nil || IsNil(o.Metrics) {
		var ret map[string]float32
		return ret
	}
	return *o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditRunDetail) GetMetricsOk() (*map[string]float32, bool) {
	if o == nil || IsNil(o.Metrics) {
		return nil, false
	}
	return o.Metrics, true
}

// HasMetrics returns a boolean if a field has been set.
func (o *GeoAuditRunDetail) HasMetrics() bool {
	if o != nil && !IsNil(o.Metrics) {
		return true
	}

	return false
}

// SetMetrics gets a reference to the given map[string]float32 and assigns it to the Metrics field.
func (o *GeoAuditRunDetail) SetMetrics(v map[string]float32) {
	o.Metrics = &v
}

// GetResultData returns the ResultData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GeoAuditRunDetail) GetResultData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.ResultData
}

// GetResultDataOk returns a tuple with the ResultData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GeoAuditRunDetail) GetResultDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ResultData) {
		return map[string]interface{}{}, false
	}
	return o.ResultData, true
}

// HasResultData returns a boolean if a field has been set.
func (o *GeoAuditRunDetail) HasResultData() bool {
	if o != nil && !IsNil(o.ResultData) {
		return true
	}

	return false
}

// SetResultData gets a reference to the given map[string]interface{} and assigns it to the ResultData field.
func (o *GeoAuditRunDetail) SetResultData(v map[string]interface{}) {
	o.ResultData = v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *GeoAuditRunDetail) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditRunDetail) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *GeoAuditRunDetail) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *GeoAuditRunDetail) SetRequestId(v string) {
	o.RequestId = &v
}

func (o GeoAuditRunDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeoAuditRunDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Sequence) {
		toSerialize["sequence"] = o.Sequence
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Trigger) {
		toSerialize["trigger"] = o.Trigger
	}
	if o.Score.IsSet() {
		toSerialize["score"] = o.Score.Get()
	}
	if o.Grade.IsSet() {
		toSerialize["grade"] = o.Grade.Get()
	}
	if o.ScoreDelta.IsSet() {
		toSerialize["score_delta"] = o.ScoreDelta.Get()
	}
	if !IsNil(o.ComparableToPrevious) {
		toSerialize["comparable_to_previous"] = o.ComparableToPrevious
	}
	if !IsNil(o.NewIssues) {
		toSerialize["new_issues"] = o.NewIssues
	}
	if !IsNil(o.FixedIssues) {
		toSerialize["fixed_issues"] = o.FixedIssues
	}
	if !IsNil(o.RegressedIssues) {
		toSerialize["regressed_issues"] = o.RegressedIssues
	}
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	if o.EngineVersion.IsSet() {
		toSerialize["engine_version"] = o.EngineVersion.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.FinishedAt.IsSet() {
		toSerialize["finished_at"] = o.FinishedAt.Get()
	}
	if !IsNil(o.AppUrl) {
		toSerialize["app_url"] = o.AppUrl
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.Metrics) {
		toSerialize["metrics"] = o.Metrics
	}
	if o.ResultData != nil {
		toSerialize["result_data"] = o.ResultData
	}
	if !IsNil(o.RequestId) {
		toSerialize["request_id"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableGeoAuditRunDetail struct {
	value *GeoAuditRunDetail
	isSet bool
}

func (v NullableGeoAuditRunDetail) Get() *GeoAuditRunDetail {
	return v.value
}

func (v *NullableGeoAuditRunDetail) Set(val *GeoAuditRunDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableGeoAuditRunDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableGeoAuditRunDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeoAuditRunDetail(val *GeoAuditRunDetail) *NullableGeoAuditRunDetail {
	return &NullableGeoAuditRunDetail{value: val, isSet: true}
}

func (v NullableGeoAuditRunDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeoAuditRunDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


