/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.56.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the PromptRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromptRecord{}

// PromptRecord struct for PromptRecord
type PromptRecord struct {
	Id int32 `json:"id"`
	PromptText string `json:"prompt_text"`
	// Primary tag, when the prompt has one
	CollectionId NullableInt32 `json:"collection_id"`
	// Every tag the prompt belongs to
	CollectionIds []int32 `json:"collection_ids"`
	Tags []TagRef `json:"tags"`
	CountryCode NullableString `json:"country_code"`
	LanguageCode NullableString `json:"language_code"`
	// Search intent: informational, navigational, commercial or transactional. Null until the prompt is classified
	PromptType NullableString `json:"prompt_type"`
	// Brand focus: brand, brand_other or non_brand. Null until the prompt is classified
	BrandKind NullableString `json:"brand_kind"`
	// Null until the prompt has run
	LastExecutedAt NullableTime `json:"last_executed_at"`
	// Opens this prompt in the app. The link names its project, so it opens there for any user with access to that project
	AppUrl string `json:"app_url"`
}

type _PromptRecord PromptRecord

// NewPromptRecord instantiates a new PromptRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromptRecord(id int32, promptText string, collectionId NullableInt32, collectionIds []int32, tags []TagRef, countryCode NullableString, languageCode NullableString, promptType NullableString, brandKind NullableString, lastExecutedAt NullableTime, appUrl string) *PromptRecord {
	this := PromptRecord{}
	this.Id = id
	this.PromptText = promptText
	this.CollectionId = collectionId
	this.CollectionIds = collectionIds
	this.Tags = tags
	this.CountryCode = countryCode
	this.LanguageCode = languageCode
	this.PromptType = promptType
	this.BrandKind = brandKind
	this.LastExecutedAt = lastExecutedAt
	this.AppUrl = appUrl
	return &this
}

// NewPromptRecordWithDefaults instantiates a new PromptRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromptRecordWithDefaults() *PromptRecord {
	this := PromptRecord{}
	return &this
}

// GetId returns the Id field value
func (o *PromptRecord) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PromptRecord) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PromptRecord) SetId(v int32) {
	o.Id = v
}

// GetPromptText returns the PromptText field value
func (o *PromptRecord) GetPromptText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PromptText
}

// GetPromptTextOk returns a tuple with the PromptText field value
// and a boolean to check if the value has been set.
func (o *PromptRecord) GetPromptTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PromptText, true
}

// SetPromptText sets field value
func (o *PromptRecord) SetPromptText(v string) {
	o.PromptText = v
}

// GetCollectionId returns the CollectionId field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *PromptRecord) GetCollectionId() int32 {
	if o == nil || o.CollectionId.Get() == nil {
		var ret int32
		return ret
	}

	return *o.CollectionId.Get()
}

// GetCollectionIdOk returns a tuple with the CollectionId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptRecord) GetCollectionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CollectionId.Get(), o.CollectionId.IsSet()
}

// SetCollectionId sets field value
func (o *PromptRecord) SetCollectionId(v int32) {
	o.CollectionId.Set(&v)
}

// GetCollectionIds returns the CollectionIds field value
func (o *PromptRecord) GetCollectionIds() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.CollectionIds
}

// GetCollectionIdsOk returns a tuple with the CollectionIds field value
// and a boolean to check if the value has been set.
func (o *PromptRecord) GetCollectionIdsOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CollectionIds, true
}

// SetCollectionIds sets field value
func (o *PromptRecord) SetCollectionIds(v []int32) {
	o.CollectionIds = v
}

// GetTags returns the Tags field value
func (o *PromptRecord) GetTags() []TagRef {
	if o == nil {
		var ret []TagRef
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *PromptRecord) GetTagsOk() ([]TagRef, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *PromptRecord) SetTags(v []TagRef) {
	o.Tags = v
}

// GetCountryCode returns the CountryCode field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PromptRecord) GetCountryCode() string {
	if o == nil || o.CountryCode.Get() == nil {
		var ret string
		return ret
	}

	return *o.CountryCode.Get()
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptRecord) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CountryCode.Get(), o.CountryCode.IsSet()
}

// SetCountryCode sets field value
func (o *PromptRecord) SetCountryCode(v string) {
	o.CountryCode.Set(&v)
}

// GetLanguageCode returns the LanguageCode field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PromptRecord) GetLanguageCode() string {
	if o == nil || o.LanguageCode.Get() == nil {
		var ret string
		return ret
	}

	return *o.LanguageCode.Get()
}

// GetLanguageCodeOk returns a tuple with the LanguageCode field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptRecord) GetLanguageCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LanguageCode.Get(), o.LanguageCode.IsSet()
}

// SetLanguageCode sets field value
func (o *PromptRecord) SetLanguageCode(v string) {
	o.LanguageCode.Set(&v)
}

// GetPromptType returns the PromptType field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PromptRecord) GetPromptType() string {
	if o == nil || o.PromptType.Get() == nil {
		var ret string
		return ret
	}

	return *o.PromptType.Get()
}

// GetPromptTypeOk returns a tuple with the PromptType field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptRecord) GetPromptTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PromptType.Get(), o.PromptType.IsSet()
}

// SetPromptType sets field value
func (o *PromptRecord) SetPromptType(v string) {
	o.PromptType.Set(&v)
}

// GetBrandKind returns the BrandKind field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PromptRecord) GetBrandKind() string {
	if o == nil || o.BrandKind.Get() == nil {
		var ret string
		return ret
	}

	return *o.BrandKind.Get()
}

// GetBrandKindOk returns a tuple with the BrandKind field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptRecord) GetBrandKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BrandKind.Get(), o.BrandKind.IsSet()
}

// SetBrandKind sets field value
func (o *PromptRecord) SetBrandKind(v string) {
	o.BrandKind.Set(&v)
}

// GetLastExecutedAt returns the LastExecutedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *PromptRecord) GetLastExecutedAt() time.Time {
	if o == nil || o.LastExecutedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastExecutedAt.Get()
}

// GetLastExecutedAtOk returns a tuple with the LastExecutedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PromptRecord) GetLastExecutedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastExecutedAt.Get(), o.LastExecutedAt.IsSet()
}

// SetLastExecutedAt sets field value
func (o *PromptRecord) SetLastExecutedAt(v time.Time) {
	o.LastExecutedAt.Set(&v)
}

// GetAppUrl returns the AppUrl field value
func (o *PromptRecord) GetAppUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppUrl
}

// GetAppUrlOk returns a tuple with the AppUrl field value
// and a boolean to check if the value has been set.
func (o *PromptRecord) GetAppUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppUrl, true
}

// SetAppUrl sets field value
func (o *PromptRecord) SetAppUrl(v string) {
	o.AppUrl = v
}

func (o PromptRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromptRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["prompt_text"] = o.PromptText
	toSerialize["collection_id"] = o.CollectionId.Get()
	toSerialize["collection_ids"] = o.CollectionIds
	toSerialize["tags"] = o.Tags
	toSerialize["country_code"] = o.CountryCode.Get()
	toSerialize["language_code"] = o.LanguageCode.Get()
	toSerialize["prompt_type"] = o.PromptType.Get()
	toSerialize["brand_kind"] = o.BrandKind.Get()
	toSerialize["last_executed_at"] = o.LastExecutedAt.Get()
	toSerialize["app_url"] = o.AppUrl
	return toSerialize, nil
}

func (o *PromptRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"prompt_text",
		"collection_id",
		"collection_ids",
		"tags",
		"country_code",
		"language_code",
		"prompt_type",
		"brand_kind",
		"last_executed_at",
		"app_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPromptRecord := _PromptRecord{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPromptRecord)

	if err != nil {
		return err
	}

	*o = PromptRecord(varPromptRecord)

	return err
}

type NullablePromptRecord struct {
	value *PromptRecord
	isSet bool
}

func (v NullablePromptRecord) Get() *PromptRecord {
	return v.value
}

func (v *NullablePromptRecord) Set(val *PromptRecord) {
	v.value = val
	v.isSet = true
}

func (v NullablePromptRecord) IsSet() bool {
	return v.isSet
}

func (v *NullablePromptRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromptRecord(val *PromptRecord) *NullablePromptRecord {
	return &NullablePromptRecord{value: val, isSet: true}
}

func (v NullablePromptRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromptRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


