/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.47.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
)

// checks if the SovResponseBreakdownInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SovResponseBreakdownInner{}

// SovResponseBreakdownInner struct for SovResponseBreakdownInner
type SovResponseBreakdownInner struct {
	Rank *int32 `json:"rank,omitempty"`
	Actor *Actor `json:"actor,omitempty"`
	Share *float32 `json:"share,omitempty"`
	Others *bool `json:"others,omitempty"`
}

// NewSovResponseBreakdownInner instantiates a new SovResponseBreakdownInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSovResponseBreakdownInner() *SovResponseBreakdownInner {
	this := SovResponseBreakdownInner{}
	return &this
}

// NewSovResponseBreakdownInnerWithDefaults instantiates a new SovResponseBreakdownInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSovResponseBreakdownInnerWithDefaults() *SovResponseBreakdownInner {
	this := SovResponseBreakdownInner{}
	return &this
}

// GetRank returns the Rank field value if set, zero value otherwise.
func (o *SovResponseBreakdownInner) GetRank() int32 {
	if o == nil || IsNil(o.Rank) {
		var ret int32
		return ret
	}
	return *o.Rank
}

// GetRankOk returns a tuple with the Rank field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SovResponseBreakdownInner) GetRankOk() (*int32, bool) {
	if o == nil || IsNil(o.Rank) {
		return nil, false
	}
	return o.Rank, true
}

// HasRank returns a boolean if a field has been set.
func (o *SovResponseBreakdownInner) HasRank() bool {
	if o != nil && !IsNil(o.Rank) {
		return true
	}

	return false
}

// SetRank gets a reference to the given int32 and assigns it to the Rank field.
func (o *SovResponseBreakdownInner) SetRank(v int32) {
	o.Rank = &v
}

// GetActor returns the Actor field value if set, zero value otherwise.
func (o *SovResponseBreakdownInner) GetActor() Actor {
	if o == nil || IsNil(o.Actor) {
		var ret Actor
		return ret
	}
	return *o.Actor
}

// GetActorOk returns a tuple with the Actor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SovResponseBreakdownInner) GetActorOk() (*Actor, bool) {
	if o == nil || IsNil(o.Actor) {
		return nil, false
	}
	return o.Actor, true
}

// HasActor returns a boolean if a field has been set.
func (o *SovResponseBreakdownInner) HasActor() bool {
	if o != nil && !IsNil(o.Actor) {
		return true
	}

	return false
}

// SetActor gets a reference to the given Actor and assigns it to the Actor field.
func (o *SovResponseBreakdownInner) SetActor(v Actor) {
	o.Actor = &v
}

// GetShare returns the Share field value if set, zero value otherwise.
func (o *SovResponseBreakdownInner) GetShare() float32 {
	if o == nil || IsNil(o.Share) {
		var ret float32
		return ret
	}
	return *o.Share
}

// GetShareOk returns a tuple with the Share field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SovResponseBreakdownInner) GetShareOk() (*float32, bool) {
	if o == nil || IsNil(o.Share) {
		return nil, false
	}
	return o.Share, true
}

// HasShare returns a boolean if a field has been set.
func (o *SovResponseBreakdownInner) HasShare() bool {
	if o != nil && !IsNil(o.Share) {
		return true
	}

	return false
}

// SetShare gets a reference to the given float32 and assigns it to the Share field.
func (o *SovResponseBreakdownInner) SetShare(v float32) {
	o.Share = &v
}

// GetOthers returns the Others field value if set, zero value otherwise.
func (o *SovResponseBreakdownInner) GetOthers() bool {
	if o == nil || IsNil(o.Others) {
		var ret bool
		return ret
	}
	return *o.Others
}

// GetOthersOk returns a tuple with the Others field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SovResponseBreakdownInner) GetOthersOk() (*bool, bool) {
	if o == nil || IsNil(o.Others) {
		return nil, false
	}
	return o.Others, true
}

// HasOthers returns a boolean if a field has been set.
func (o *SovResponseBreakdownInner) HasOthers() bool {
	if o != nil && !IsNil(o.Others) {
		return true
	}

	return false
}

// SetOthers gets a reference to the given bool and assigns it to the Others field.
func (o *SovResponseBreakdownInner) SetOthers(v bool) {
	o.Others = &v
}

func (o SovResponseBreakdownInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SovResponseBreakdownInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Rank) {
		toSerialize["rank"] = o.Rank
	}
	if !IsNil(o.Actor) {
		toSerialize["actor"] = o.Actor
	}
	if !IsNil(o.Share) {
		toSerialize["share"] = o.Share
	}
	if !IsNil(o.Others) {
		toSerialize["others"] = o.Others
	}
	return toSerialize, nil
}

type NullableSovResponseBreakdownInner struct {
	value *SovResponseBreakdownInner
	isSet bool
}

func (v NullableSovResponseBreakdownInner) Get() *SovResponseBreakdownInner {
	return v.value
}

func (v *NullableSovResponseBreakdownInner) Set(val *SovResponseBreakdownInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSovResponseBreakdownInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSovResponseBreakdownInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSovResponseBreakdownInner(val *SovResponseBreakdownInner) *NullableSovResponseBreakdownInner {
	return &NullableSovResponseBreakdownInner{value: val, isSet: true}
}

func (v NullableSovResponseBreakdownInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSovResponseBreakdownInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


