/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.57.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SearchConsoleFiltersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchConsoleFiltersInner{}

// SearchConsoleFiltersInner struct for SearchConsoleFiltersInner
type SearchConsoleFiltersInner struct {
	Dimension string `json:"dimension"`
	Operator *string `json:"operator,omitempty"`
	Expression string `json:"expression"`
}

type _SearchConsoleFiltersInner SearchConsoleFiltersInner

// NewSearchConsoleFiltersInner instantiates a new SearchConsoleFiltersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchConsoleFiltersInner(dimension string, expression string) *SearchConsoleFiltersInner {
	this := SearchConsoleFiltersInner{}
	this.Dimension = dimension
	var operator string = "contains"
	this.Operator = &operator
	this.Expression = expression
	return &this
}

// NewSearchConsoleFiltersInnerWithDefaults instantiates a new SearchConsoleFiltersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchConsoleFiltersInnerWithDefaults() *SearchConsoleFiltersInner {
	this := SearchConsoleFiltersInner{}
	var operator string = "contains"
	this.Operator = &operator
	return &this
}

// GetDimension returns the Dimension field value
func (o *SearchConsoleFiltersInner) GetDimension() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Dimension
}

// GetDimensionOk returns a tuple with the Dimension field value
// and a boolean to check if the value has been set.
func (o *SearchConsoleFiltersInner) GetDimensionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dimension, true
}

// SetDimension sets field value
func (o *SearchConsoleFiltersInner) SetDimension(v string) {
	o.Dimension = v
}

// GetOperator returns the Operator field value if set, zero value otherwise.
func (o *SearchConsoleFiltersInner) GetOperator() string {
	if o == nil || IsNil(o.Operator) {
		var ret string
		return ret
	}
	return *o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchConsoleFiltersInner) GetOperatorOk() (*string, bool) {
	if o == nil || IsNil(o.Operator) {
		return nil, false
	}
	return o.Operator, true
}

// HasOperator returns a boolean if a field has been set.
func (o *SearchConsoleFiltersInner) HasOperator() bool {
	if o != nil && !IsNil(o.Operator) {
		return true
	}

	return false
}

// SetOperator gets a reference to the given string and assigns it to the Operator field.
func (o *SearchConsoleFiltersInner) SetOperator(v string) {
	o.Operator = &v
}

// GetExpression returns the Expression field value
func (o *SearchConsoleFiltersInner) GetExpression() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Expression
}

// GetExpressionOk returns a tuple with the Expression field value
// and a boolean to check if the value has been set.
func (o *SearchConsoleFiltersInner) GetExpressionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expression, true
}

// SetExpression sets field value
func (o *SearchConsoleFiltersInner) SetExpression(v string) {
	o.Expression = v
}

func (o SearchConsoleFiltersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchConsoleFiltersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dimension"] = o.Dimension
	if !IsNil(o.Operator) {
		toSerialize["operator"] = o.Operator
	}
	toSerialize["expression"] = o.Expression
	return toSerialize, nil
}

func (o *SearchConsoleFiltersInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dimension",
		"expression",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchConsoleFiltersInner := _SearchConsoleFiltersInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSearchConsoleFiltersInner)

	if err != nil {
		return err
	}

	*o = SearchConsoleFiltersInner(varSearchConsoleFiltersInner)

	return err
}

type NullableSearchConsoleFiltersInner struct {
	value *SearchConsoleFiltersInner
	isSet bool
}

func (v NullableSearchConsoleFiltersInner) Get() *SearchConsoleFiltersInner {
	return v.value
}

func (v *NullableSearchConsoleFiltersInner) Set(val *SearchConsoleFiltersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchConsoleFiltersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchConsoleFiltersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchConsoleFiltersInner(val *SearchConsoleFiltersInner) *NullableSearchConsoleFiltersInner {
	return &NullableSearchConsoleFiltersInner{value: val, isSet: true}
}

func (v NullableSearchConsoleFiltersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchConsoleFiltersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


