/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.57.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
)

// checks if the LocalBusinessesTotals type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocalBusinessesTotals{}

// LocalBusinessesTotals struct for LocalBusinessesTotals
type LocalBusinessesTotals struct {
	Businesses *int32 `json:"businesses,omitempty"`
	YourBusinesses *int32 `json:"your_businesses,omitempty"`
	Appearances *int32 `json:"appearances,omitempty"`
	AvgRating NullableFloat32 `json:"avg_rating,omitempty"`
	ExecutionsWithLocalBusinesses *int32 `json:"executions_with_local_businesses,omitempty"`
}

// NewLocalBusinessesTotals instantiates a new LocalBusinessesTotals object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocalBusinessesTotals() *LocalBusinessesTotals {
	this := LocalBusinessesTotals{}
	return &this
}

// NewLocalBusinessesTotalsWithDefaults instantiates a new LocalBusinessesTotals object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocalBusinessesTotalsWithDefaults() *LocalBusinessesTotals {
	this := LocalBusinessesTotals{}
	return &this
}

// GetBusinesses returns the Businesses field value if set, zero value otherwise.
func (o *LocalBusinessesTotals) GetBusinesses() int32 {
	if o == nil || IsNil(o.Businesses) {
		var ret int32
		return ret
	}
	return *o.Businesses
}

// GetBusinessesOk returns a tuple with the Businesses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalBusinessesTotals) GetBusinessesOk() (*int32, bool) {
	if o == nil || IsNil(o.Businesses) {
		return nil, false
	}
	return o.Businesses, true
}

// HasBusinesses returns a boolean if a field has been set.
func (o *LocalBusinessesTotals) HasBusinesses() bool {
	if o != nil && !IsNil(o.Businesses) {
		return true
	}

	return false
}

// SetBusinesses gets a reference to the given int32 and assigns it to the Businesses field.
func (o *LocalBusinessesTotals) SetBusinesses(v int32) {
	o.Businesses = &v
}

// GetYourBusinesses returns the YourBusinesses field value if set, zero value otherwise.
func (o *LocalBusinessesTotals) GetYourBusinesses() int32 {
	if o == nil || IsNil(o.YourBusinesses) {
		var ret int32
		return ret
	}
	return *o.YourBusinesses
}

// GetYourBusinessesOk returns a tuple with the YourBusinesses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalBusinessesTotals) GetYourBusinessesOk() (*int32, bool) {
	if o == nil || IsNil(o.YourBusinesses) {
		return nil, false
	}
	return o.YourBusinesses, true
}

// HasYourBusinesses returns a boolean if a field has been set.
func (o *LocalBusinessesTotals) HasYourBusinesses() bool {
	if o != nil && !IsNil(o.YourBusinesses) {
		return true
	}

	return false
}

// SetYourBusinesses gets a reference to the given int32 and assigns it to the YourBusinesses field.
func (o *LocalBusinessesTotals) SetYourBusinesses(v int32) {
	o.YourBusinesses = &v
}

// GetAppearances returns the Appearances field value if set, zero value otherwise.
func (o *LocalBusinessesTotals) GetAppearances() int32 {
	if o == nil || IsNil(o.Appearances) {
		var ret int32
		return ret
	}
	return *o.Appearances
}

// GetAppearancesOk returns a tuple with the Appearances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalBusinessesTotals) GetAppearancesOk() (*int32, bool) {
	if o == nil || IsNil(o.Appearances) {
		return nil, false
	}
	return o.Appearances, true
}

// HasAppearances returns a boolean if a field has been set.
func (o *LocalBusinessesTotals) HasAppearances() bool {
	if o != nil && !IsNil(o.Appearances) {
		return true
	}

	return false
}

// SetAppearances gets a reference to the given int32 and assigns it to the Appearances field.
func (o *LocalBusinessesTotals) SetAppearances(v int32) {
	o.Appearances = &v
}

// GetAvgRating returns the AvgRating field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LocalBusinessesTotals) GetAvgRating() float32 {
	if o == nil || IsNil(o.AvgRating.Get()) {
		var ret float32
		return ret
	}
	return *o.AvgRating.Get()
}

// GetAvgRatingOk returns a tuple with the AvgRating field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LocalBusinessesTotals) GetAvgRatingOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvgRating.Get(), o.AvgRating.IsSet()
}

// HasAvgRating returns a boolean if a field has been set.
func (o *LocalBusinessesTotals) HasAvgRating() bool {
	if o != nil && o.AvgRating.IsSet() {
		return true
	}

	return false
}

// SetAvgRating gets a reference to the given NullableFloat32 and assigns it to the AvgRating field.
func (o *LocalBusinessesTotals) SetAvgRating(v float32) {
	o.AvgRating.Set(&v)
}
// SetAvgRatingNil sets the value for AvgRating to be an explicit nil
func (o *LocalBusinessesTotals) SetAvgRatingNil() {
	o.AvgRating.Set(nil)
}

// UnsetAvgRating ensures that no value is present for AvgRating, not even an explicit nil
func (o *LocalBusinessesTotals) UnsetAvgRating() {
	o.AvgRating.Unset()
}

// GetExecutionsWithLocalBusinesses returns the ExecutionsWithLocalBusinesses field value if set, zero value otherwise.
func (o *LocalBusinessesTotals) GetExecutionsWithLocalBusinesses() int32 {
	if o == nil || IsNil(o.ExecutionsWithLocalBusinesses) {
		var ret int32
		return ret
	}
	return *o.ExecutionsWithLocalBusinesses
}

// GetExecutionsWithLocalBusinessesOk returns a tuple with the ExecutionsWithLocalBusinesses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalBusinessesTotals) GetExecutionsWithLocalBusinessesOk() (*int32, bool) {
	if o == nil || IsNil(o.ExecutionsWithLocalBusinesses) {
		return nil, false
	}
	return o.ExecutionsWithLocalBusinesses, true
}

// HasExecutionsWithLocalBusinesses returns a boolean if a field has been set.
func (o *LocalBusinessesTotals) HasExecutionsWithLocalBusinesses() bool {
	if o != nil && !IsNil(o.ExecutionsWithLocalBusinesses) {
		return true
	}

	return false
}

// SetExecutionsWithLocalBusinesses gets a reference to the given int32 and assigns it to the ExecutionsWithLocalBusinesses field.
func (o *LocalBusinessesTotals) SetExecutionsWithLocalBusinesses(v int32) {
	o.ExecutionsWithLocalBusinesses = &v
}

func (o LocalBusinessesTotals) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocalBusinessesTotals) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Businesses) {
		toSerialize["businesses"] = o.Businesses
	}
	if !IsNil(o.YourBusinesses) {
		toSerialize["your_businesses"] = o.YourBusinesses
	}
	if !IsNil(o.Appearances) {
		toSerialize["appearances"] = o.Appearances
	}
	if o.AvgRating.IsSet() {
		toSerialize["avg_rating"] = o.AvgRating.Get()
	}
	if !IsNil(o.ExecutionsWithLocalBusinesses) {
		toSerialize["executions_with_local_businesses"] = o.ExecutionsWithLocalBusinesses
	}
	return toSerialize, nil
}

type NullableLocalBusinessesTotals struct {
	value *LocalBusinessesTotals
	isSet bool
}

func (v NullableLocalBusinessesTotals) Get() *LocalBusinessesTotals {
	return v.value
}

func (v *NullableLocalBusinessesTotals) Set(val *LocalBusinessesTotals) {
	v.value = val
	v.isSet = true
}

func (v NullableLocalBusinessesTotals) IsSet() bool {
	return v.isSet
}

func (v *NullableLocalBusinessesTotals) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocalBusinessesTotals(val *LocalBusinessesTotals) *NullableLocalBusinessesTotals {
	return &NullableLocalBusinessesTotals{value: val, isSet: true}
}

func (v NullableLocalBusinessesTotals) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocalBusinessesTotals) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


