/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.57.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"time"
)

// checks if the GeoAuditResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeoAuditResponse{}

// GeoAuditResponse struct for GeoAuditResponse
type GeoAuditResponse struct {
	// Stable audit id
	Id *string `json:"id,omitempty"`
	AuditType *string `json:"audit_type,omitempty"`
	// The audited domain (site-wide types) or page URL, normalized
	Target *string `json:"target,omitempty"`
	CountryCode NullableString `json:"country_code,omitempty"`
	Cadence *string `json:"cadence,omitempty"`
	Status *string `json:"status,omitempty"`
	// user, or unreachable when three runs in a row could not reach the site
	PausedReason NullableString `json:"paused_reason,omitempty"`
	Schedule NullableGeoAuditSchedule `json:"schedule,omitempty"`
	NextRunAt NullableTime `json:"next_run_at,omitempty"`
	EmailAlerts *bool `json:"email_alerts,omitempty"`
	// Whether this audit type can run weekly or monthly
	RecurringAvailable *bool `json:"recurring_available,omitempty"`
	// Whether runs of this type produce findings and issues, or a score only
	ChecksTracked *bool `json:"checks_tracked,omitempty"`
	LatestRun NullableGeoAuditRun `json:"latest_run,omitempty"`
	OpenIssues *int32 `json:"open_issues,omitempty"`
	OpenCriticalIssues *int32 `json:"open_critical_issues,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	AppUrl *string `json:"app_url,omitempty"`
	ProjectId *int32 `json:"project_id,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
}

// NewGeoAuditResponse instantiates a new GeoAuditResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeoAuditResponse() *GeoAuditResponse {
	this := GeoAuditResponse{}
	return &this
}

// NewGeoAuditResponseWithDefaults instantiates a new GeoAuditResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeoAuditResponseWithDefaults() *GeoAuditResponse {
	this := GeoAuditResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GeoAuditResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GeoAuditResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GeoAuditResponse) SetId(v string) {
	o.Id = &v
}

// GetAuditType returns the AuditType field value if set, zero value otherwise.
func (o *GeoAuditResponse) GetAuditType() string {
	if o == nil || IsNil(o.AuditType) {
		var ret string
		return ret
	}
	return *o.AuditType
}

// GetAuditTypeOk returns a tuple with the AuditType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditResponse) GetAuditTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AuditType) {
		return nil, false
	}
	return o.AuditType, true
}

// HasAuditType returns a boolean if a field has been set.
func (o *GeoAuditResponse) HasAuditType() bool {
	if o != nil && !IsNil(o.AuditType) {
		return true
	}

	return false
}

// SetAuditType gets a reference to the given string and assigns it to the AuditType field.
func (o *GeoAuditResponse) SetAuditType(v string) {
	o.AuditType = &v
}

// GetTarget returns the Target field value if set, zero value otherwise.
func (o *GeoAuditResponse) GetTarget() string {
	if o == nil || IsNil(o.Target) {
		var ret string
		return ret
	}
	return *o.Target
}

// GetTargetOk returns a tuple with the Target field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditResponse) GetTargetOk() (*string, bool) {
	if o == nil || IsNil(o.Target) {
		return nil, false
	}
	return o.Target, true
}

// HasTarget returns a boolean if a field has been set.
func (o *GeoAuditResponse) HasTarget() bool {
	if o != nil && !IsNil(o.Target) {
		return true
	}

	return false
}

// SetTarget gets a reference to the given string and assigns it to the Target field.
func (o *GeoAuditResponse) SetTarget(v string) {
	o.Target = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GeoAuditResponse) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode.Get()) {
		var ret string
		return ret
	}
	return *o.CountryCode.Get()
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GeoAuditResponse) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CountryCode.Get(), o.CountryCode.IsSet()
}

// HasCountryCode returns a boolean if a field has been set.
func (o *GeoAuditResponse) HasCountryCode() bool {
	if o != nil && o.CountryCode.IsSet() {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given NullableString and assigns it to the CountryCode field.
func (o *GeoAuditResponse) SetCountryCode(v string) {
	o.CountryCode.Set(&v)
}
// SetCountryCodeNil sets the value for CountryCode to be an explicit nil
func (o *GeoAuditResponse) SetCountryCodeNil() {
	o.CountryCode.Set(nil)
}

// UnsetCountryCode ensures that no value is present for CountryCode, not even an explicit nil
func (o *GeoAuditResponse) UnsetCountryCode() {
	o.CountryCode.Unset()
}

// GetCadence returns the Cadence field value if set, zero value otherwise.
func (o *GeoAuditResponse) GetCadence() string {
	if o == nil || IsNil(o.Cadence) {
		var ret string
		return ret
	}
	return *o.Cadence
}

// GetCadenceOk returns a tuple with the Cadence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditResponse) GetCadenceOk() (*string, bool) {
	if o == nil || IsNil(o.Cadence) {
		return nil, false
	}
	return o.Cadence, true
}

// HasCadence returns a boolean if a field has been set.
func (o *GeoAuditResponse) HasCadence() bool {
	if o != nil && !IsNil(o.Cadence) {
		return true
	}

	return false
}

// SetCadence gets a reference to the given string and assigns it to the Cadence field.
func (o *GeoAuditResponse) SetCadence(v string) {
	o.Cadence = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GeoAuditResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GeoAuditResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GeoAuditResponse) SetStatus(v string) {
	o.Status = &v
}

// GetPausedReason returns the PausedReason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GeoAuditResponse) GetPausedReason() string {
	if o == nil || IsNil(o.PausedReason.Get()) {
		var ret string
		return ret
	}
	return *o.PausedReason.Get()
}

// GetPausedReasonOk returns a tuple with the PausedReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GeoAuditResponse) GetPausedReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PausedReason.Get(), o.PausedReason.IsSet()
}

// HasPausedReason returns a boolean if a field has been set.
func (o *GeoAuditResponse) HasPausedReason() bool {
	if o != nil && o.PausedReason.IsSet() {
		return true
	}

	return false
}

// SetPausedReason gets a reference to the given NullableString and assigns it to the PausedReason field.
func (o *GeoAuditResponse) SetPausedReason(v string) {
	o.PausedReason.Set(&v)
}
// SetPausedReasonNil sets the value for PausedReason to be an explicit nil
func (o *GeoAuditResponse) SetPausedReasonNil() {
	o.PausedReason.Set(nil)
}

// UnsetPausedReason ensures that no value is present for PausedReason, not even an explicit nil
func (o *GeoAuditResponse) UnsetPausedReason() {
	o.PausedReason.Unset()
}

// GetSchedule returns the Schedule field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GeoAuditResponse) GetSchedule() GeoAuditSchedule {
	if o == nil || IsNil(o.Schedule.Get()) {
		var ret GeoAuditSchedule
		return ret
	}
	return *o.Schedule.Get()
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GeoAuditResponse) GetScheduleOk() (*GeoAuditSchedule, bool) {
	if o == nil {
		return nil, false
	}
	return o.Schedule.Get(), o.Schedule.IsSet()
}

// HasSchedule returns a boolean if a field has been set.
func (o *GeoAuditResponse) HasSchedule() bool {
	if o != nil && o.Schedule.IsSet() {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given NullableGeoAuditSchedule and assigns it to the Schedule field.
func (o *GeoAuditResponse) SetSchedule(v GeoAuditSchedule) {
	o.Schedule.Set(&v)
}
// SetScheduleNil sets the value for Schedule to be an explicit nil
func (o *GeoAuditResponse) SetScheduleNil() {
	o.Schedule.Set(nil)
}

// UnsetSchedule ensures that no value is present for Schedule, not even an explicit nil
func (o *GeoAuditResponse) UnsetSchedule() {
	o.Schedule.Unset()
}

// GetNextRunAt returns the NextRunAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GeoAuditResponse) GetNextRunAt() time.Time {
	if o == nil || IsNil(o.NextRunAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.NextRunAt.Get()
}

// GetNextRunAtOk returns a tuple with the NextRunAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GeoAuditResponse) GetNextRunAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextRunAt.Get(), o.NextRunAt.IsSet()
}

// HasNextRunAt returns a boolean if a field has been set.
func (o *GeoAuditResponse) HasNextRunAt() bool {
	if o != nil && o.NextRunAt.IsSet() {
		return true
	}

	return false
}

// SetNextRunAt gets a reference to the given NullableTime and assigns it to the NextRunAt field.
func (o *GeoAuditResponse) SetNextRunAt(v time.Time) {
	o.NextRunAt.Set(&v)
}
// SetNextRunAtNil sets the value for NextRunAt to be an explicit nil
func (o *GeoAuditResponse) SetNextRunAtNil() {
	o.NextRunAt.Set(nil)
}

// UnsetNextRunAt ensures that no value is present for NextRunAt, not even an explicit nil
func (o *GeoAuditResponse) UnsetNextRunAt() {
	o.NextRunAt.Unset()
}

// GetEmailAlerts returns the EmailAlerts field value if set, zero value otherwise.
func (o *GeoAuditResponse) GetEmailAlerts() bool {
	if o == nil || IsNil(o.EmailAlerts) {
		var ret bool
		return ret
	}
	return *o.EmailAlerts
}

// GetEmailAlertsOk returns a tuple with the EmailAlerts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditResponse) GetEmailAlertsOk() (*bool, bool) {
	if o == nil || IsNil(o.EmailAlerts) {
		return nil, false
	}
	return o.EmailAlerts, true
}

// HasEmailAlerts returns a boolean if a field has been set.
func (o *GeoAuditResponse) HasEmailAlerts() bool {
	if o != nil && !IsNil(o.EmailAlerts) {
		return true
	}

	return false
}

// SetEmailAlerts gets a reference to the given bool and assigns it to the EmailAlerts field.
func (o *GeoAuditResponse) SetEmailAlerts(v bool) {
	o.EmailAlerts = &v
}

// GetRecurringAvailable returns the RecurringAvailable field value if set, zero value otherwise.
func (o *GeoAuditResponse) GetRecurringAvailable() bool {
	if o == nil || IsNil(o.RecurringAvailable) {
		var ret bool
		return ret
	}
	return *o.RecurringAvailable
}

// GetRecurringAvailableOk returns a tuple with the RecurringAvailable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditResponse) GetRecurringAvailableOk() (*bool, bool) {
	if o == nil || IsNil(o.RecurringAvailable) {
		return nil, false
	}
	return o.RecurringAvailable, true
}

// HasRecurringAvailable returns a boolean if a field has been set.
func (o *GeoAuditResponse) HasRecurringAvailable() bool {
	if o != nil && !IsNil(o.RecurringAvailable) {
		return true
	}

	return false
}

// SetRecurringAvailable gets a reference to the given bool and assigns it to the RecurringAvailable field.
func (o *GeoAuditResponse) SetRecurringAvailable(v bool) {
	o.RecurringAvailable = &v
}

// GetChecksTracked returns the ChecksTracked field value if set, zero value otherwise.
func (o *GeoAuditResponse) GetChecksTracked() bool {
	if o == nil || IsNil(o.ChecksTracked) {
		var ret bool
		return ret
	}
	return *o.ChecksTracked
}

// GetChecksTrackedOk returns a tuple with the ChecksTracked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditResponse) GetChecksTrackedOk() (*bool, bool) {
	if o == nil || IsNil(o.ChecksTracked) {
		return nil, false
	}
	return o.ChecksTracked, true
}

// HasChecksTracked returns a boolean if a field has been set.
func (o *GeoAuditResponse) HasChecksTracked() bool {
	if o != nil && !IsNil(o.ChecksTracked) {
		return true
	}

	return false
}

// SetChecksTracked gets a reference to the given bool and assigns it to the ChecksTracked field.
func (o *GeoAuditResponse) SetChecksTracked(v bool) {
	o.ChecksTracked = &v
}

// GetLatestRun returns the LatestRun field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GeoAuditResponse) GetLatestRun() GeoAuditRun {
	if o == nil || IsNil(o.LatestRun.Get()) {
		var ret GeoAuditRun
		return ret
	}
	return *o.LatestRun.Get()
}

// GetLatestRunOk returns a tuple with the LatestRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GeoAuditResponse) GetLatestRunOk() (*GeoAuditRun, bool) {
	if o == nil {
		return nil, false
	}
	return o.LatestRun.Get(), o.LatestRun.IsSet()
}

// HasLatestRun returns a boolean if a field has been set.
func (o *GeoAuditResponse) HasLatestRun() bool {
	if o != nil && o.LatestRun.IsSet() {
		return true
	}

	return false
}

// SetLatestRun gets a reference to the given NullableGeoAuditRun and assigns it to the LatestRun field.
func (o *GeoAuditResponse) SetLatestRun(v GeoAuditRun) {
	o.LatestRun.Set(&v)
}
// SetLatestRunNil sets the value for LatestRun to be an explicit nil
func (o *GeoAuditResponse) SetLatestRunNil() {
	o.LatestRun.Set(nil)
}

// UnsetLatestRun ensures that no value is present for LatestRun, not even an explicit nil
func (o *GeoAuditResponse) UnsetLatestRun() {
	o.LatestRun.Unset()
}

// GetOpenIssues returns the OpenIssues field value if set, zero value otherwise.
func (o *GeoAuditResponse) GetOpenIssues() int32 {
	if o == nil || IsNil(o.OpenIssues) {
		var ret int32
		return ret
	}
	return *o.OpenIssues
}

// GetOpenIssuesOk returns a tuple with the OpenIssues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditResponse) GetOpenIssuesOk() (*int32, bool) {
	if o == nil || IsNil(o.OpenIssues) {
		return nil, false
	}
	return o.OpenIssues, true
}

// HasOpenIssues returns a boolean if a field has been set.
func (o *GeoAuditResponse) HasOpenIssues() bool {
	if o != nil && !IsNil(o.OpenIssues) {
		return true
	}

	return false
}

// SetOpenIssues gets a reference to the given int32 and assigns it to the OpenIssues field.
func (o *GeoAuditResponse) SetOpenIssues(v int32) {
	o.OpenIssues = &v
}

// GetOpenCriticalIssues returns the OpenCriticalIssues field value if set, zero value otherwise.
func (o *GeoAuditResponse) GetOpenCriticalIssues() int32 {
	if o == nil || IsNil(o.OpenCriticalIssues) {
		var ret int32
		return ret
	}
	return *o.OpenCriticalIssues
}

// GetOpenCriticalIssuesOk returns a tuple with the OpenCriticalIssues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditResponse) GetOpenCriticalIssuesOk() (*int32, bool) {
	if o == nil || IsNil(o.OpenCriticalIssues) {
		return nil, false
	}
	return o.OpenCriticalIssues, true
}

// HasOpenCriticalIssues returns a boolean if a field has been set.
func (o *GeoAuditResponse) HasOpenCriticalIssues() bool {
	if o != nil && !IsNil(o.OpenCriticalIssues) {
		return true
	}

	return false
}

// SetOpenCriticalIssues gets a reference to the given int32 and assigns it to the OpenCriticalIssues field.
func (o *GeoAuditResponse) SetOpenCriticalIssues(v int32) {
	o.OpenCriticalIssues = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GeoAuditResponse) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GeoAuditResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *GeoAuditResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetAppUrl returns the AppUrl field value if set, zero value otherwise.
func (o *GeoAuditResponse) GetAppUrl() string {
	if o == nil || IsNil(o.AppUrl) {
		var ret string
		return ret
	}
	return *o.AppUrl
}

// GetAppUrlOk returns a tuple with the AppUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditResponse) GetAppUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AppUrl) {
		return nil, false
	}
	return o.AppUrl, true
}

// HasAppUrl returns a boolean if a field has been set.
func (o *GeoAuditResponse) HasAppUrl() bool {
	if o != nil && !IsNil(o.AppUrl) {
		return true
	}

	return false
}

// SetAppUrl gets a reference to the given string and assigns it to the AppUrl field.
func (o *GeoAuditResponse) SetAppUrl(v string) {
	o.AppUrl = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *GeoAuditResponse) GetProjectId() int32 {
	if o == nil || IsNil(o.ProjectId) {
		var ret int32
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditResponse) GetProjectIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *GeoAuditResponse) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given int32 and assigns it to the ProjectId field.
func (o *GeoAuditResponse) SetProjectId(v int32) {
	o.ProjectId = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *GeoAuditResponse) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *GeoAuditResponse) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *GeoAuditResponse) SetRequestId(v string) {
	o.RequestId = &v
}

func (o GeoAuditResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeoAuditResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.AuditType) {
		toSerialize["audit_type"] = o.AuditType
	}
	if !IsNil(o.Target) {
		toSerialize["target"] = o.Target
	}
	if o.CountryCode.IsSet() {
		toSerialize["country_code"] = o.CountryCode.Get()
	}
	if !IsNil(o.Cadence) {
		toSerialize["cadence"] = o.Cadence
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.PausedReason.IsSet() {
		toSerialize["paused_reason"] = o.PausedReason.Get()
	}
	if o.Schedule.IsSet() {
		toSerialize["schedule"] = o.Schedule.Get()
	}
	if o.NextRunAt.IsSet() {
		toSerialize["next_run_at"] = o.NextRunAt.Get()
	}
	if !IsNil(o.EmailAlerts) {
		toSerialize["email_alerts"] = o.EmailAlerts
	}
	if !IsNil(o.RecurringAvailable) {
		toSerialize["recurring_available"] = o.RecurringAvailable
	}
	if !IsNil(o.ChecksTracked) {
		toSerialize["checks_tracked"] = o.ChecksTracked
	}
	if o.LatestRun.IsSet() {
		toSerialize["latest_run"] = o.LatestRun.Get()
	}
	if !IsNil(o.OpenIssues) {
		toSerialize["open_issues"] = o.OpenIssues
	}
	if !IsNil(o.OpenCriticalIssues) {
		toSerialize["open_critical_issues"] = o.OpenCriticalIssues
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.AppUrl) {
		toSerialize["app_url"] = o.AppUrl
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.RequestId) {
		toSerialize["request_id"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableGeoAuditResponse struct {
	value *GeoAuditResponse
	isSet bool
}

func (v NullableGeoAuditResponse) Get() *GeoAuditResponse {
	return v.value
}

func (v *NullableGeoAuditResponse) Set(val *GeoAuditResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGeoAuditResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGeoAuditResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeoAuditResponse(val *GeoAuditResponse) *NullableGeoAuditResponse {
	return &NullableGeoAuditResponse{value: val, isSet: true}
}

func (v NullableGeoAuditResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeoAuditResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


