/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.57.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PromptTagsAssignResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromptTagsAssignResponse{}

// PromptTagsAssignResponse struct for PromptTagsAssignResponse
type PromptTagsAssignResponse struct {
	ProjectId int32 `json:"project_id"`
	// Prompts of the project among prompt_ids
	PromptsTargeted int32 `json:"prompts_targeted"`
	TagsAttached []TagRef `json:"tags_attached"`
	NewLinksCreated int32 `json:"new_links_created"`
	SkippedAlreadyLinked int32 `json:"skipped_already_linked"`
	// tag_names that matched no tag and were not created
	MissingTagNames []string `json:"missing_tag_names"`
	// prompt_ids that are not prompts of this project
	IgnoredPromptIds []int32 `json:"ignored_prompt_ids"`
	RequestId string `json:"request_id"`
}

type _PromptTagsAssignResponse PromptTagsAssignResponse

// NewPromptTagsAssignResponse instantiates a new PromptTagsAssignResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromptTagsAssignResponse(projectId int32, promptsTargeted int32, tagsAttached []TagRef, newLinksCreated int32, skippedAlreadyLinked int32, missingTagNames []string, ignoredPromptIds []int32, requestId string) *PromptTagsAssignResponse {
	this := PromptTagsAssignResponse{}
	this.ProjectId = projectId
	this.PromptsTargeted = promptsTargeted
	this.TagsAttached = tagsAttached
	this.NewLinksCreated = newLinksCreated
	this.SkippedAlreadyLinked = skippedAlreadyLinked
	this.MissingTagNames = missingTagNames
	this.IgnoredPromptIds = ignoredPromptIds
	this.RequestId = requestId
	return &this
}

// NewPromptTagsAssignResponseWithDefaults instantiates a new PromptTagsAssignResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromptTagsAssignResponseWithDefaults() *PromptTagsAssignResponse {
	this := PromptTagsAssignResponse{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *PromptTagsAssignResponse) GetProjectId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *PromptTagsAssignResponse) GetProjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *PromptTagsAssignResponse) SetProjectId(v int32) {
	o.ProjectId = v
}

// GetPromptsTargeted returns the PromptsTargeted field value
func (o *PromptTagsAssignResponse) GetPromptsTargeted() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PromptsTargeted
}

// GetPromptsTargetedOk returns a tuple with the PromptsTargeted field value
// and a boolean to check if the value has been set.
func (o *PromptTagsAssignResponse) GetPromptsTargetedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PromptsTargeted, true
}

// SetPromptsTargeted sets field value
func (o *PromptTagsAssignResponse) SetPromptsTargeted(v int32) {
	o.PromptsTargeted = v
}

// GetTagsAttached returns the TagsAttached field value
func (o *PromptTagsAssignResponse) GetTagsAttached() []TagRef {
	if o == nil {
		var ret []TagRef
		return ret
	}

	return o.TagsAttached
}

// GetTagsAttachedOk returns a tuple with the TagsAttached field value
// and a boolean to check if the value has been set.
func (o *PromptTagsAssignResponse) GetTagsAttachedOk() ([]TagRef, bool) {
	if o == nil {
		return nil, false
	}
	return o.TagsAttached, true
}

// SetTagsAttached sets field value
func (o *PromptTagsAssignResponse) SetTagsAttached(v []TagRef) {
	o.TagsAttached = v
}

// GetNewLinksCreated returns the NewLinksCreated field value
func (o *PromptTagsAssignResponse) GetNewLinksCreated() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NewLinksCreated
}

// GetNewLinksCreatedOk returns a tuple with the NewLinksCreated field value
// and a boolean to check if the value has been set.
func (o *PromptTagsAssignResponse) GetNewLinksCreatedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewLinksCreated, true
}

// SetNewLinksCreated sets field value
func (o *PromptTagsAssignResponse) SetNewLinksCreated(v int32) {
	o.NewLinksCreated = v
}

// GetSkippedAlreadyLinked returns the SkippedAlreadyLinked field value
func (o *PromptTagsAssignResponse) GetSkippedAlreadyLinked() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SkippedAlreadyLinked
}

// GetSkippedAlreadyLinkedOk returns a tuple with the SkippedAlreadyLinked field value
// and a boolean to check if the value has been set.
func (o *PromptTagsAssignResponse) GetSkippedAlreadyLinkedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SkippedAlreadyLinked, true
}

// SetSkippedAlreadyLinked sets field value
func (o *PromptTagsAssignResponse) SetSkippedAlreadyLinked(v int32) {
	o.SkippedAlreadyLinked = v
}

// GetMissingTagNames returns the MissingTagNames field value
func (o *PromptTagsAssignResponse) GetMissingTagNames() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.MissingTagNames
}

// GetMissingTagNamesOk returns a tuple with the MissingTagNames field value
// and a boolean to check if the value has been set.
func (o *PromptTagsAssignResponse) GetMissingTagNamesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MissingTagNames, true
}

// SetMissingTagNames sets field value
func (o *PromptTagsAssignResponse) SetMissingTagNames(v []string) {
	o.MissingTagNames = v
}

// GetIgnoredPromptIds returns the IgnoredPromptIds field value
func (o *PromptTagsAssignResponse) GetIgnoredPromptIds() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.IgnoredPromptIds
}

// GetIgnoredPromptIdsOk returns a tuple with the IgnoredPromptIds field value
// and a boolean to check if the value has been set.
func (o *PromptTagsAssignResponse) GetIgnoredPromptIdsOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.IgnoredPromptIds, true
}

// SetIgnoredPromptIds sets field value
func (o *PromptTagsAssignResponse) SetIgnoredPromptIds(v []int32) {
	o.IgnoredPromptIds = v
}

// GetRequestId returns the RequestId field value
func (o *PromptTagsAssignResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *PromptTagsAssignResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *PromptTagsAssignResponse) SetRequestId(v string) {
	o.RequestId = v
}

func (o PromptTagsAssignResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromptTagsAssignResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["prompts_targeted"] = o.PromptsTargeted
	toSerialize["tags_attached"] = o.TagsAttached
	toSerialize["new_links_created"] = o.NewLinksCreated
	toSerialize["skipped_already_linked"] = o.SkippedAlreadyLinked
	toSerialize["missing_tag_names"] = o.MissingTagNames
	toSerialize["ignored_prompt_ids"] = o.IgnoredPromptIds
	toSerialize["request_id"] = o.RequestId
	return toSerialize, nil
}

func (o *PromptTagsAssignResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"prompts_targeted",
		"tags_attached",
		"new_links_created",
		"skipped_already_linked",
		"missing_tag_names",
		"ignored_prompt_ids",
		"request_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPromptTagsAssignResponse := _PromptTagsAssignResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPromptTagsAssignResponse)

	if err != nil {
		return err
	}

	*o = PromptTagsAssignResponse(varPromptTagsAssignResponse)

	return err
}

type NullablePromptTagsAssignResponse struct {
	value *PromptTagsAssignResponse
	isSet bool
}

func (v NullablePromptTagsAssignResponse) Get() *PromptTagsAssignResponse {
	return v.value
}

func (v *NullablePromptTagsAssignResponse) Set(val *PromptTagsAssignResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePromptTagsAssignResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePromptTagsAssignResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromptTagsAssignResponse(val *PromptTagsAssignResponse) *NullablePromptTagsAssignResponse {
	return &NullablePromptTagsAssignResponse{value: val, isSet: true}
}

func (v NullablePromptTagsAssignResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromptTagsAssignResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


