/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.57.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"time"
)

// checks if the WebAnalyticsQueryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebAnalyticsQueryResponse{}

// WebAnalyticsQueryResponse struct for WebAnalyticsQueryResponse
type WebAnalyticsQueryResponse struct {
	ProjectId *int32 `json:"project_id,omitempty"`
	Provider *string `json:"provider,omitempty"`
	Property *string `json:"property,omitempty"`
	Columns []WebAnalyticsQueryResponseColumnsInner `json:"columns,omitempty"`
	// One array per row, values in column order: strings, numbers or null.
	Rows [][]interface{} `json:"rows,omitempty"`
	// Rows in this response (at most 5,000).
	RowCount *int32 `json:"row_count,omitempty"`
	// Rows the provider has for the query, when it reports it.
	TotalRows *int32 `json:"total_rows,omitempty"`
	// True when the provider has more rows than returned; page with its own offset or page field.
	Truncated *bool `json:"truncated,omitempty"`
	// Metric totals by metric name, when the query asked for them.
	Totals map[string]interface{} `json:"totals,omitempty"`
	// Provider caveats: sampling, thresholds, more rows available.
	Notes []string `json:"notes,omitempty"`
	// Provider metadata such as GA4 time zone, currency and remaining property quota.
	Meta map[string]interface{} `json:"meta,omitempty"`
	// When the provider answered.
	FetchedAt *time.Time `json:"fetched_at,omitempty"`
	// True when the answer came from the 10-minute cache instead of the provider.
	Cached *bool `json:"cached,omitempty"`
	// The request as sent to the provider, with the connected property forced and limits applied.
	Query map[string]interface{} `json:"query,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
}

// NewWebAnalyticsQueryResponse instantiates a new WebAnalyticsQueryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebAnalyticsQueryResponse() *WebAnalyticsQueryResponse {
	this := WebAnalyticsQueryResponse{}
	return &this
}

// NewWebAnalyticsQueryResponseWithDefaults instantiates a new WebAnalyticsQueryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebAnalyticsQueryResponseWithDefaults() *WebAnalyticsQueryResponse {
	this := WebAnalyticsQueryResponse{}
	return &this
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *WebAnalyticsQueryResponse) GetProjectId() int32 {
	if o == nil || IsNil(o.ProjectId) {
		var ret int32
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebAnalyticsQueryResponse) GetProjectIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *WebAnalyticsQueryResponse) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given int32 and assigns it to the ProjectId field.
func (o *WebAnalyticsQueryResponse) SetProjectId(v int32) {
	o.ProjectId = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *WebAnalyticsQueryResponse) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebAnalyticsQueryResponse) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *WebAnalyticsQueryResponse) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *WebAnalyticsQueryResponse) SetProvider(v string) {
	o.Provider = &v
}

// GetProperty returns the Property field value if set, zero value otherwise.
func (o *WebAnalyticsQueryResponse) GetProperty() string {
	if o == nil || IsNil(o.Property) {
		var ret string
		return ret
	}
	return *o.Property
}

// GetPropertyOk returns a tuple with the Property field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebAnalyticsQueryResponse) GetPropertyOk() (*string, bool) {
	if o == nil || IsNil(o.Property) {
		return nil, false
	}
	return o.Property, true
}

// HasProperty returns a boolean if a field has been set.
func (o *WebAnalyticsQueryResponse) HasProperty() bool {
	if o != nil && !IsNil(o.Property) {
		return true
	}

	return false
}

// SetProperty gets a reference to the given string and assigns it to the Property field.
func (o *WebAnalyticsQueryResponse) SetProperty(v string) {
	o.Property = &v
}

// GetColumns returns the Columns field value if set, zero value otherwise.
func (o *WebAnalyticsQueryResponse) GetColumns() []WebAnalyticsQueryResponseColumnsInner {
	if o == nil || IsNil(o.Columns) {
		var ret []WebAnalyticsQueryResponseColumnsInner
		return ret
	}
	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebAnalyticsQueryResponse) GetColumnsOk() ([]WebAnalyticsQueryResponseColumnsInner, bool) {
	if o == nil || IsNil(o.Columns) {
		return nil, false
	}
	return o.Columns, true
}

// HasColumns returns a boolean if a field has been set.
func (o *WebAnalyticsQueryResponse) HasColumns() bool {
	if o != nil && !IsNil(o.Columns) {
		return true
	}

	return false
}

// SetColumns gets a reference to the given []WebAnalyticsQueryResponseColumnsInner and assigns it to the Columns field.
func (o *WebAnalyticsQueryResponse) SetColumns(v []WebAnalyticsQueryResponseColumnsInner) {
	o.Columns = v
}

// GetRows returns the Rows field value if set, zero value otherwise.
func (o *WebAnalyticsQueryResponse) GetRows() [][]interface{} {
	if o == nil || IsNil(o.Rows) {
		var ret [][]interface{}
		return ret
	}
	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebAnalyticsQueryResponse) GetRowsOk() ([][]interface{}, bool) {
	if o == nil || IsNil(o.Rows) {
		return nil, false
	}
	return o.Rows, true
}

// HasRows returns a boolean if a field has been set.
func (o *WebAnalyticsQueryResponse) HasRows() bool {
	if o != nil && !IsNil(o.Rows) {
		return true
	}

	return false
}

// SetRows gets a reference to the given [][]interface{} and assigns it to the Rows field.
func (o *WebAnalyticsQueryResponse) SetRows(v [][]interface{}) {
	o.Rows = v
}

// GetRowCount returns the RowCount field value if set, zero value otherwise.
func (o *WebAnalyticsQueryResponse) GetRowCount() int32 {
	if o == nil || IsNil(o.RowCount) {
		var ret int32
		return ret
	}
	return *o.RowCount
}

// GetRowCountOk returns a tuple with the RowCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebAnalyticsQueryResponse) GetRowCountOk() (*int32, bool) {
	if o == nil || IsNil(o.RowCount) {
		return nil, false
	}
	return o.RowCount, true
}

// HasRowCount returns a boolean if a field has been set.
func (o *WebAnalyticsQueryResponse) HasRowCount() bool {
	if o != nil && !IsNil(o.RowCount) {
		return true
	}

	return false
}

// SetRowCount gets a reference to the given int32 and assigns it to the RowCount field.
func (o *WebAnalyticsQueryResponse) SetRowCount(v int32) {
	o.RowCount = &v
}

// GetTotalRows returns the TotalRows field value if set, zero value otherwise.
func (o *WebAnalyticsQueryResponse) GetTotalRows() int32 {
	if o == nil || IsNil(o.TotalRows) {
		var ret int32
		return ret
	}
	return *o.TotalRows
}

// GetTotalRowsOk returns a tuple with the TotalRows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebAnalyticsQueryResponse) GetTotalRowsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalRows) {
		return nil, false
	}
	return o.TotalRows, true
}

// HasTotalRows returns a boolean if a field has been set.
func (o *WebAnalyticsQueryResponse) HasTotalRows() bool {
	if o != nil && !IsNil(o.TotalRows) {
		return true
	}

	return false
}

// SetTotalRows gets a reference to the given int32 and assigns it to the TotalRows field.
func (o *WebAnalyticsQueryResponse) SetTotalRows(v int32) {
	o.TotalRows = &v
}

// GetTruncated returns the Truncated field value if set, zero value otherwise.
func (o *WebAnalyticsQueryResponse) GetTruncated() bool {
	if o == nil || IsNil(o.Truncated) {
		var ret bool
		return ret
	}
	return *o.Truncated
}

// GetTruncatedOk returns a tuple with the Truncated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebAnalyticsQueryResponse) GetTruncatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Truncated) {
		return nil, false
	}
	return o.Truncated, true
}

// HasTruncated returns a boolean if a field has been set.
func (o *WebAnalyticsQueryResponse) HasTruncated() bool {
	if o != nil && !IsNil(o.Truncated) {
		return true
	}

	return false
}

// SetTruncated gets a reference to the given bool and assigns it to the Truncated field.
func (o *WebAnalyticsQueryResponse) SetTruncated(v bool) {
	o.Truncated = &v
}

// GetTotals returns the Totals field value if set, zero value otherwise.
func (o *WebAnalyticsQueryResponse) GetTotals() map[string]interface{} {
	if o == nil || IsNil(o.Totals) {
		var ret map[string]interface{}
		return ret
	}
	return o.Totals
}

// GetTotalsOk returns a tuple with the Totals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebAnalyticsQueryResponse) GetTotalsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Totals) {
		return map[string]interface{}{}, false
	}
	return o.Totals, true
}

// HasTotals returns a boolean if a field has been set.
func (o *WebAnalyticsQueryResponse) HasTotals() bool {
	if o != nil && !IsNil(o.Totals) {
		return true
	}

	return false
}

// SetTotals gets a reference to the given map[string]interface{} and assigns it to the Totals field.
func (o *WebAnalyticsQueryResponse) SetTotals(v map[string]interface{}) {
	o.Totals = v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *WebAnalyticsQueryResponse) GetNotes() []string {
	if o == nil || IsNil(o.Notes) {
		var ret []string
		return ret
	}
	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebAnalyticsQueryResponse) GetNotesOk() ([]string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *WebAnalyticsQueryResponse) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given []string and assigns it to the Notes field.
func (o *WebAnalyticsQueryResponse) SetNotes(v []string) {
	o.Notes = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *WebAnalyticsQueryResponse) GetMeta() map[string]interface{} {
	if o == nil || IsNil(o.Meta) {
		var ret map[string]interface{}
		return ret
	}
	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebAnalyticsQueryResponse) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Meta) {
		return map[string]interface{}{}, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *WebAnalyticsQueryResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given map[string]interface{} and assigns it to the Meta field.
func (o *WebAnalyticsQueryResponse) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

// GetFetchedAt returns the FetchedAt field value if set, zero value otherwise.
func (o *WebAnalyticsQueryResponse) GetFetchedAt() time.Time {
	if o == nil || IsNil(o.FetchedAt) {
		var ret time.Time
		return ret
	}
	return *o.FetchedAt
}

// GetFetchedAtOk returns a tuple with the FetchedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebAnalyticsQueryResponse) GetFetchedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.FetchedAt) {
		return nil, false
	}
	return o.FetchedAt, true
}

// HasFetchedAt returns a boolean if a field has been set.
func (o *WebAnalyticsQueryResponse) HasFetchedAt() bool {
	if o != nil && !IsNil(o.FetchedAt) {
		return true
	}

	return false
}

// SetFetchedAt gets a reference to the given time.Time and assigns it to the FetchedAt field.
func (o *WebAnalyticsQueryResponse) SetFetchedAt(v time.Time) {
	o.FetchedAt = &v
}

// GetCached returns the Cached field value if set, zero value otherwise.
func (o *WebAnalyticsQueryResponse) GetCached() bool {
	if o == nil || IsNil(o.Cached) {
		var ret bool
		return ret
	}
	return *o.Cached
}

// GetCachedOk returns a tuple with the Cached field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebAnalyticsQueryResponse) GetCachedOk() (*bool, bool) {
	if o == nil || IsNil(o.Cached) {
		return nil, false
	}
	return o.Cached, true
}

// HasCached returns a boolean if a field has been set.
func (o *WebAnalyticsQueryResponse) HasCached() bool {
	if o != nil && !IsNil(o.Cached) {
		return true
	}

	return false
}

// SetCached gets a reference to the given bool and assigns it to the Cached field.
func (o *WebAnalyticsQueryResponse) SetCached(v bool) {
	o.Cached = &v
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *WebAnalyticsQueryResponse) GetQuery() map[string]interface{} {
	if o == nil || IsNil(o.Query) {
		var ret map[string]interface{}
		return ret
	}
	return o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebAnalyticsQueryResponse) GetQueryOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Query) {
		return map[string]interface{}{}, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *WebAnalyticsQueryResponse) HasQuery() bool {
	if o != nil && !IsNil(o.Query) {
		return true
	}

	return false
}

// SetQuery gets a reference to the given map[string]interface{} and assigns it to the Query field.
func (o *WebAnalyticsQueryResponse) SetQuery(v map[string]interface{}) {
	o.Query = v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *WebAnalyticsQueryResponse) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebAnalyticsQueryResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *WebAnalyticsQueryResponse) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *WebAnalyticsQueryResponse) SetRequestId(v string) {
	o.RequestId = &v
}

func (o WebAnalyticsQueryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebAnalyticsQueryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.Property) {
		toSerialize["property"] = o.Property
	}
	if !IsNil(o.Columns) {
		toSerialize["columns"] = o.Columns
	}
	if !IsNil(o.Rows) {
		toSerialize["rows"] = o.Rows
	}
	if !IsNil(o.RowCount) {
		toSerialize["row_count"] = o.RowCount
	}
	if !IsNil(o.TotalRows) {
		toSerialize["total_rows"] = o.TotalRows
	}
	if !IsNil(o.Truncated) {
		toSerialize["truncated"] = o.Truncated
	}
	if !IsNil(o.Totals) {
		toSerialize["totals"] = o.Totals
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.FetchedAt) {
		toSerialize["fetched_at"] = o.FetchedAt
	}
	if !IsNil(o.Cached) {
		toSerialize["cached"] = o.Cached
	}
	if !IsNil(o.Query) {
		toSerialize["query"] = o.Query
	}
	if !IsNil(o.RequestId) {
		toSerialize["request_id"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableWebAnalyticsQueryResponse struct {
	value *WebAnalyticsQueryResponse
	isSet bool
}

func (v NullableWebAnalyticsQueryResponse) Get() *WebAnalyticsQueryResponse {
	return v.value
}

func (v *NullableWebAnalyticsQueryResponse) Set(val *WebAnalyticsQueryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebAnalyticsQueryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebAnalyticsQueryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebAnalyticsQueryResponse(val *WebAnalyticsQueryResponse) *NullableWebAnalyticsQueryResponse {
	return &NullableWebAnalyticsQueryResponse{value: val, isSet: true}
}

func (v NullableWebAnalyticsQueryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebAnalyticsQueryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


