/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.56.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ModelsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsResponse{}

// ModelsResponse struct for ModelsResponse
type ModelsResponse struct {
	ProjectId int32 `json:"project_id"`
	Models []string `json:"models"`
	RequestId string `json:"request_id"`
}

type _ModelsResponse ModelsResponse

// NewModelsResponse instantiates a new ModelsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsResponse(projectId int32, models []string, requestId string) *ModelsResponse {
	this := ModelsResponse{}
	this.ProjectId = projectId
	this.Models = models
	this.RequestId = requestId
	return &this
}

// NewModelsResponseWithDefaults instantiates a new ModelsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsResponseWithDefaults() *ModelsResponse {
	this := ModelsResponse{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *ModelsResponse) GetProjectId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *ModelsResponse) GetProjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *ModelsResponse) SetProjectId(v int32) {
	o.ProjectId = v
}

// GetModels returns the Models field value
func (o *ModelsResponse) GetModels() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Models
}

// GetModelsOk returns a tuple with the Models field value
// and a boolean to check if the value has been set.
func (o *ModelsResponse) GetModelsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Models, true
}

// SetModels sets field value
func (o *ModelsResponse) SetModels(v []string) {
	o.Models = v
}

// GetRequestId returns the RequestId field value
func (o *ModelsResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *ModelsResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *ModelsResponse) SetRequestId(v string) {
	o.RequestId = v
}

func (o ModelsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["models"] = o.Models
	toSerialize["request_id"] = o.RequestId
	return toSerialize, nil
}

func (o *ModelsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"models",
		"request_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelsResponse := _ModelsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelsResponse)

	if err != nil {
		return err
	}

	*o = ModelsResponse(varModelsResponse)

	return err
}

type NullableModelsResponse struct {
	value *ModelsResponse
	isSet bool
}

func (v NullableModelsResponse) Get() *ModelsResponse {
	return v.value
}

func (v *NullableModelsResponse) Set(val *ModelsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsResponse(val *ModelsResponse) *NullableModelsResponse {
	return &NullableModelsResponse{value: val, isSet: true}
}

func (v NullableModelsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


