/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.56.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LocalesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocalesResponse{}

// LocalesResponse struct for LocalesResponse
type LocalesResponse struct {
	ProjectId int32 `json:"project_id"`
	// Country codes with data
	Countries []string `json:"countries"`
	// Language codes with data
	Languages []string `json:"languages"`
	RequestId string `json:"request_id"`
}

type _LocalesResponse LocalesResponse

// NewLocalesResponse instantiates a new LocalesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocalesResponse(projectId int32, countries []string, languages []string, requestId string) *LocalesResponse {
	this := LocalesResponse{}
	this.ProjectId = projectId
	this.Countries = countries
	this.Languages = languages
	this.RequestId = requestId
	return &this
}

// NewLocalesResponseWithDefaults instantiates a new LocalesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocalesResponseWithDefaults() *LocalesResponse {
	this := LocalesResponse{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *LocalesResponse) GetProjectId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *LocalesResponse) GetProjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *LocalesResponse) SetProjectId(v int32) {
	o.ProjectId = v
}

// GetCountries returns the Countries field value
func (o *LocalesResponse) GetCountries() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Countries
}

// GetCountriesOk returns a tuple with the Countries field value
// and a boolean to check if the value has been set.
func (o *LocalesResponse) GetCountriesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Countries, true
}

// SetCountries sets field value
func (o *LocalesResponse) SetCountries(v []string) {
	o.Countries = v
}

// GetLanguages returns the Languages field value
func (o *LocalesResponse) GetLanguages() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Languages
}

// GetLanguagesOk returns a tuple with the Languages field value
// and a boolean to check if the value has been set.
func (o *LocalesResponse) GetLanguagesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Languages, true
}

// SetLanguages sets field value
func (o *LocalesResponse) SetLanguages(v []string) {
	o.Languages = v
}

// GetRequestId returns the RequestId field value
func (o *LocalesResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *LocalesResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *LocalesResponse) SetRequestId(v string) {
	o.RequestId = v
}

func (o LocalesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocalesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["countries"] = o.Countries
	toSerialize["languages"] = o.Languages
	toSerialize["request_id"] = o.RequestId
	return toSerialize, nil
}

func (o *LocalesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"countries",
		"languages",
		"request_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLocalesResponse := _LocalesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLocalesResponse)

	if err != nil {
		return err
	}

	*o = LocalesResponse(varLocalesResponse)

	return err
}

type NullableLocalesResponse struct {
	value *LocalesResponse
	isSet bool
}

func (v NullableLocalesResponse) Get() *LocalesResponse {
	return v.value
}

func (v *NullableLocalesResponse) Set(val *LocalesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLocalesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLocalesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocalesResponse(val *LocalesResponse) *NullableLocalesResponse {
	return &NullableLocalesResponse{value: val, isSet: true}
}

func (v NullableLocalesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocalesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


