/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.57.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TagRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagRef{}

// TagRef struct for TagRef
type TagRef struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
}

type _TagRef TagRef

// NewTagRef instantiates a new TagRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagRef(id int32, name string) *TagRef {
	this := TagRef{}
	this.Id = id
	this.Name = name
	return &this
}

// NewTagRefWithDefaults instantiates a new TagRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagRefWithDefaults() *TagRef {
	this := TagRef{}
	return &this
}

// GetId returns the Id field value
func (o *TagRef) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TagRef) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TagRef) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *TagRef) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TagRef) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TagRef) SetName(v string) {
	o.Name = v
}

func (o TagRef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *TagRef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTagRef := _TagRef{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTagRef)

	if err != nil {
		return err
	}

	*o = TagRef(varTagRef)

	return err
}

type NullableTagRef struct {
	value *TagRef
	isSet bool
}

func (v NullableTagRef) Get() *TagRef {
	return v.value
}

func (v *NullableTagRef) Set(val *TagRef) {
	v.value = val
	v.isSet = true
}

func (v NullableTagRef) IsSet() bool {
	return v.isSet
}

func (v *NullableTagRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagRef(val *TagRef) *NullableTagRef {
	return &NullableTagRef{value: val, isSet: true}
}

func (v NullableTagRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


