/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.46.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"time"
)

// checks if the TopSourcesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TopSourcesResponse{}

// TopSourcesResponse struct for TopSourcesResponse
type TopSourcesResponse struct {
	ProjectId *int32 `json:"project_id,omitempty"`
	From *time.Time `json:"from,omitempty"`
	To *time.Time `json:"to,omitempty"`
	Sort *string `json:"sort,omitempty"`
	Page *int32 `json:"page,omitempty"`
	PerPage *int32 `json:"per_page,omitempty"`
	Total *int32 `json:"total,omitempty"`
	Data []TopSourcesResponseDataInner `json:"data,omitempty"`
}

// NewTopSourcesResponse instantiates a new TopSourcesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTopSourcesResponse() *TopSourcesResponse {
	this := TopSourcesResponse{}
	return &this
}

// NewTopSourcesResponseWithDefaults instantiates a new TopSourcesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTopSourcesResponseWithDefaults() *TopSourcesResponse {
	this := TopSourcesResponse{}
	return &this
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *TopSourcesResponse) GetProjectId() int32 {
	if o == nil || IsNil(o.ProjectId) {
		var ret int32
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopSourcesResponse) GetProjectIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *TopSourcesResponse) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given int32 and assigns it to the ProjectId field.
func (o *TopSourcesResponse) SetProjectId(v int32) {
	o.ProjectId = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *TopSourcesResponse) GetFrom() time.Time {
	if o == nil || IsNil(o.From) {
		var ret time.Time
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopSourcesResponse) GetFromOk() (*time.Time, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *TopSourcesResponse) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given time.Time and assigns it to the From field.
func (o *TopSourcesResponse) SetFrom(v time.Time) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *TopSourcesResponse) GetTo() time.Time {
	if o == nil || IsNil(o.To) {
		var ret time.Time
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopSourcesResponse) GetToOk() (*time.Time, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *TopSourcesResponse) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given time.Time and assigns it to the To field.
func (o *TopSourcesResponse) SetTo(v time.Time) {
	o.To = &v
}

// GetSort returns the Sort field value if set, zero value otherwise.
func (o *TopSourcesResponse) GetSort() string {
	if o == nil || IsNil(o.Sort) {
		var ret string
		return ret
	}
	return *o.Sort
}

// GetSortOk returns a tuple with the Sort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopSourcesResponse) GetSortOk() (*string, bool) {
	if o == nil || IsNil(o.Sort) {
		return nil, false
	}
	return o.Sort, true
}

// HasSort returns a boolean if a field has been set.
func (o *TopSourcesResponse) HasSort() bool {
	if o != nil && !IsNil(o.Sort) {
		return true
	}

	return false
}

// SetSort gets a reference to the given string and assigns it to the Sort field.
func (o *TopSourcesResponse) SetSort(v string) {
	o.Sort = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *TopSourcesResponse) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopSourcesResponse) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *TopSourcesResponse) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *TopSourcesResponse) SetPage(v int32) {
	o.Page = &v
}

// GetPerPage returns the PerPage field value if set, zero value otherwise.
func (o *TopSourcesResponse) GetPerPage() int32 {
	if o == nil || IsNil(o.PerPage) {
		var ret int32
		return ret
	}
	return *o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopSourcesResponse) GetPerPageOk() (*int32, bool) {
	if o == nil || IsNil(o.PerPage) {
		return nil, false
	}
	return o.PerPage, true
}

// HasPerPage returns a boolean if a field has been set.
func (o *TopSourcesResponse) HasPerPage() bool {
	if o != nil && !IsNil(o.PerPage) {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given int32 and assigns it to the PerPage field.
func (o *TopSourcesResponse) SetPerPage(v int32) {
	o.PerPage = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *TopSourcesResponse) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopSourcesResponse) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *TopSourcesResponse) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *TopSourcesResponse) SetTotal(v int32) {
	o.Total = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *TopSourcesResponse) GetData() []TopSourcesResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []TopSourcesResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopSourcesResponse) GetDataOk() ([]TopSourcesResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *TopSourcesResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []TopSourcesResponseDataInner and assigns it to the Data field.
func (o *TopSourcesResponse) SetData(v []TopSourcesResponseDataInner) {
	o.Data = v
}

func (o TopSourcesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TopSourcesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	if !IsNil(o.Sort) {
		toSerialize["sort"] = o.Sort
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.PerPage) {
		toSerialize["per_page"] = o.PerPage
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableTopSourcesResponse struct {
	value *TopSourcesResponse
	isSet bool
}

func (v NullableTopSourcesResponse) Get() *TopSourcesResponse {
	return v.value
}

func (v *NullableTopSourcesResponse) Set(val *TopSourcesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTopSourcesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTopSourcesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTopSourcesResponse(val *TopSourcesResponse) *NullableTopSourcesResponse {
	return &NullableTopSourcesResponse{value: val, isSet: true}
}

func (v NullableTopSourcesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTopSourcesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


