/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.56.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StoreConnectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoreConnectionResponse{}

// StoreConnectionResponse struct for StoreConnectionResponse
type StoreConnectionResponse struct {
	// The store platform, e.g. shopify
	Platform string `json:"platform"`
	// The store domain as compared: lowercase, without scheme, www or path
	Domain string `json:"domain"`
	Project NullableStoreConnectionResponseProject `json:"project"`
	// True when several live projects match the store domain (for example one project per market). project is then null and the app asks the key holder to pick from candidates.
	Ambiguous bool `json:"ambiguous"`
	// Every live project of the account, for a project picker
	Candidates []StoreConnectionResponseCandidatesInner `json:"candidates"`
	Account StoreConnectionResponseAccount `json:"account"`
	RequestId string `json:"request_id"`
}

type _StoreConnectionResponse StoreConnectionResponse

// NewStoreConnectionResponse instantiates a new StoreConnectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoreConnectionResponse(platform string, domain string, project NullableStoreConnectionResponseProject, ambiguous bool, candidates []StoreConnectionResponseCandidatesInner, account StoreConnectionResponseAccount, requestId string) *StoreConnectionResponse {
	this := StoreConnectionResponse{}
	this.Platform = platform
	this.Domain = domain
	this.Project = project
	this.Ambiguous = ambiguous
	this.Candidates = candidates
	this.Account = account
	this.RequestId = requestId
	return &this
}

// NewStoreConnectionResponseWithDefaults instantiates a new StoreConnectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoreConnectionResponseWithDefaults() *StoreConnectionResponse {
	this := StoreConnectionResponse{}
	return &this
}

// GetPlatform returns the Platform field value
func (o *StoreConnectionResponse) GetPlatform() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value
// and a boolean to check if the value has been set.
func (o *StoreConnectionResponse) GetPlatformOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Platform, true
}

// SetPlatform sets field value
func (o *StoreConnectionResponse) SetPlatform(v string) {
	o.Platform = v
}

// GetDomain returns the Domain field value
func (o *StoreConnectionResponse) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *StoreConnectionResponse) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *StoreConnectionResponse) SetDomain(v string) {
	o.Domain = v
}

// GetProject returns the Project field value
// If the value is explicit nil, the zero value for StoreConnectionResponseProject will be returned
func (o *StoreConnectionResponse) GetProject() StoreConnectionResponseProject {
	if o == nil || o.Project.Get() == nil {
		var ret StoreConnectionResponseProject
		return ret
	}

	return *o.Project.Get()
}

// GetProjectOk returns a tuple with the Project field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoreConnectionResponse) GetProjectOk() (*StoreConnectionResponseProject, bool) {
	if o == nil {
		return nil, false
	}
	return o.Project.Get(), o.Project.IsSet()
}

// SetProject sets field value
func (o *StoreConnectionResponse) SetProject(v StoreConnectionResponseProject) {
	o.Project.Set(&v)
}

// GetAmbiguous returns the Ambiguous field value
func (o *StoreConnectionResponse) GetAmbiguous() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Ambiguous
}

// GetAmbiguousOk returns a tuple with the Ambiguous field value
// and a boolean to check if the value has been set.
func (o *StoreConnectionResponse) GetAmbiguousOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ambiguous, true
}

// SetAmbiguous sets field value
func (o *StoreConnectionResponse) SetAmbiguous(v bool) {
	o.Ambiguous = v
}

// GetCandidates returns the Candidates field value
func (o *StoreConnectionResponse) GetCandidates() []StoreConnectionResponseCandidatesInner {
	if o == nil {
		var ret []StoreConnectionResponseCandidatesInner
		return ret
	}

	return o.Candidates
}

// GetCandidatesOk returns a tuple with the Candidates field value
// and a boolean to check if the value has been set.
func (o *StoreConnectionResponse) GetCandidatesOk() ([]StoreConnectionResponseCandidatesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Candidates, true
}

// SetCandidates sets field value
func (o *StoreConnectionResponse) SetCandidates(v []StoreConnectionResponseCandidatesInner) {
	o.Candidates = v
}

// GetAccount returns the Account field value
func (o *StoreConnectionResponse) GetAccount() StoreConnectionResponseAccount {
	if o == nil {
		var ret StoreConnectionResponseAccount
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *StoreConnectionResponse) GetAccountOk() (*StoreConnectionResponseAccount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *StoreConnectionResponse) SetAccount(v StoreConnectionResponseAccount) {
	o.Account = v
}

// GetRequestId returns the RequestId field value
func (o *StoreConnectionResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *StoreConnectionResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *StoreConnectionResponse) SetRequestId(v string) {
	o.RequestId = v
}

func (o StoreConnectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoreConnectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["platform"] = o.Platform
	toSerialize["domain"] = o.Domain
	toSerialize["project"] = o.Project.Get()
	toSerialize["ambiguous"] = o.Ambiguous
	toSerialize["candidates"] = o.Candidates
	toSerialize["account"] = o.Account
	toSerialize["request_id"] = o.RequestId
	return toSerialize, nil
}

func (o *StoreConnectionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"platform",
		"domain",
		"project",
		"ambiguous",
		"candidates",
		"account",
		"request_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStoreConnectionResponse := _StoreConnectionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStoreConnectionResponse)

	if err != nil {
		return err
	}

	*o = StoreConnectionResponse(varStoreConnectionResponse)

	return err
}

type NullableStoreConnectionResponse struct {
	value *StoreConnectionResponse
	isSet bool
}

func (v NullableStoreConnectionResponse) Get() *StoreConnectionResponse {
	return v.value
}

func (v *NullableStoreConnectionResponse) Set(val *StoreConnectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStoreConnectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStoreConnectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoreConnectionResponse(val *StoreConnectionResponse) *NullableStoreConnectionResponse {
	return &NullableStoreConnectionResponse{value: val, isSet: true}
}

func (v NullableStoreConnectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoreConnectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


