/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.57.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"time"
)

// checks if the SummaryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SummaryResponse{}

// SummaryResponse struct for SummaryResponse
type SummaryResponse struct {
	ProjectId *int32 `json:"project_id,omitempty"`
	From *time.Time `json:"from,omitempty"`
	To *time.Time `json:"to,omitempty"`
	// day, week or month
	Granularity *string `json:"granularity,omitempty"`
	Filters *MetricsFiltersEcho `json:"filters,omitempty"`
	Series *map[string][]TimeseriesSeries `json:"series,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
	Summary *map[string][]SummaryResponseAllOfSummaryValueInner `json:"summary,omitempty"`
	PositionDistribution *SummaryResponseAllOfPositionDistribution `json:"position_distribution,omitempty"`
}

// NewSummaryResponse instantiates a new SummaryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSummaryResponse() *SummaryResponse {
	this := SummaryResponse{}
	return &this
}

// NewSummaryResponseWithDefaults instantiates a new SummaryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSummaryResponseWithDefaults() *SummaryResponse {
	this := SummaryResponse{}
	return &this
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *SummaryResponse) GetProjectId() int32 {
	if o == nil || IsNil(o.ProjectId) {
		var ret int32
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryResponse) GetProjectIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *SummaryResponse) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given int32 and assigns it to the ProjectId field.
func (o *SummaryResponse) SetProjectId(v int32) {
	o.ProjectId = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *SummaryResponse) GetFrom() time.Time {
	if o == nil || IsNil(o.From) {
		var ret time.Time
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryResponse) GetFromOk() (*time.Time, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *SummaryResponse) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given time.Time and assigns it to the From field.
func (o *SummaryResponse) SetFrom(v time.Time) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *SummaryResponse) GetTo() time.Time {
	if o == nil || IsNil(o.To) {
		var ret time.Time
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryResponse) GetToOk() (*time.Time, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *SummaryResponse) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given time.Time and assigns it to the To field.
func (o *SummaryResponse) SetTo(v time.Time) {
	o.To = &v
}

// GetGranularity returns the Granularity field value if set, zero value otherwise.
func (o *SummaryResponse) GetGranularity() string {
	if o == nil || IsNil(o.Granularity) {
		var ret string
		return ret
	}
	return *o.Granularity
}

// GetGranularityOk returns a tuple with the Granularity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryResponse) GetGranularityOk() (*string, bool) {
	if o == nil || IsNil(o.Granularity) {
		return nil, false
	}
	return o.Granularity, true
}

// HasGranularity returns a boolean if a field has been set.
func (o *SummaryResponse) HasGranularity() bool {
	if o != nil && !IsNil(o.Granularity) {
		return true
	}

	return false
}

// SetGranularity gets a reference to the given string and assigns it to the Granularity field.
func (o *SummaryResponse) SetGranularity(v string) {
	o.Granularity = &v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *SummaryResponse) GetFilters() MetricsFiltersEcho {
	if o == nil || IsNil(o.Filters) {
		var ret MetricsFiltersEcho
		return ret
	}
	return *o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryResponse) GetFiltersOk() (*MetricsFiltersEcho, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *SummaryResponse) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given MetricsFiltersEcho and assigns it to the Filters field.
func (o *SummaryResponse) SetFilters(v MetricsFiltersEcho) {
	o.Filters = &v
}

// GetSeries returns the Series field value if set, zero value otherwise.
func (o *SummaryResponse) GetSeries() map[string][]TimeseriesSeries {
	if o == nil || IsNil(o.Series) {
		var ret map[string][]TimeseriesSeries
		return ret
	}
	return *o.Series
}

// GetSeriesOk returns a tuple with the Series field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryResponse) GetSeriesOk() (*map[string][]TimeseriesSeries, bool) {
	if o == nil || IsNil(o.Series) {
		return nil, false
	}
	return o.Series, true
}

// HasSeries returns a boolean if a field has been set.
func (o *SummaryResponse) HasSeries() bool {
	if o != nil && !IsNil(o.Series) {
		return true
	}

	return false
}

// SetSeries gets a reference to the given map[string][]TimeseriesSeries and assigns it to the Series field.
func (o *SummaryResponse) SetSeries(v map[string][]TimeseriesSeries) {
	o.Series = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *SummaryResponse) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *SummaryResponse) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *SummaryResponse) SetRequestId(v string) {
	o.RequestId = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *SummaryResponse) GetSummary() map[string][]SummaryResponseAllOfSummaryValueInner {
	if o == nil || IsNil(o.Summary) {
		var ret map[string][]SummaryResponseAllOfSummaryValueInner
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryResponse) GetSummaryOk() (*map[string][]SummaryResponseAllOfSummaryValueInner, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *SummaryResponse) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given map[string][]SummaryResponseAllOfSummaryValueInner and assigns it to the Summary field.
func (o *SummaryResponse) SetSummary(v map[string][]SummaryResponseAllOfSummaryValueInner) {
	o.Summary = &v
}

// GetPositionDistribution returns the PositionDistribution field value if set, zero value otherwise.
func (o *SummaryResponse) GetPositionDistribution() SummaryResponseAllOfPositionDistribution {
	if o == nil || IsNil(o.PositionDistribution) {
		var ret SummaryResponseAllOfPositionDistribution
		return ret
	}
	return *o.PositionDistribution
}

// GetPositionDistributionOk returns a tuple with the PositionDistribution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummaryResponse) GetPositionDistributionOk() (*SummaryResponseAllOfPositionDistribution, bool) {
	if o == nil || IsNil(o.PositionDistribution) {
		return nil, false
	}
	return o.PositionDistribution, true
}

// HasPositionDistribution returns a boolean if a field has been set.
func (o *SummaryResponse) HasPositionDistribution() bool {
	if o != nil && !IsNil(o.PositionDistribution) {
		return true
	}

	return false
}

// SetPositionDistribution gets a reference to the given SummaryResponseAllOfPositionDistribution and assigns it to the PositionDistribution field.
func (o *SummaryResponse) SetPositionDistribution(v SummaryResponseAllOfPositionDistribution) {
	o.PositionDistribution = &v
}

func (o SummaryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SummaryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	if !IsNil(o.Granularity) {
		toSerialize["granularity"] = o.Granularity
	}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	if !IsNil(o.Series) {
		toSerialize["series"] = o.Series
	}
	if !IsNil(o.RequestId) {
		toSerialize["request_id"] = o.RequestId
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.PositionDistribution) {
		toSerialize["position_distribution"] = o.PositionDistribution
	}
	return toSerialize, nil
}

type NullableSummaryResponse struct {
	value *SummaryResponse
	isSet bool
}

func (v NullableSummaryResponse) Get() *SummaryResponse {
	return v.value
}

func (v *NullableSummaryResponse) Set(val *SummaryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSummaryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSummaryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSummaryResponse(val *SummaryResponse) *NullableSummaryResponse {
	return &NullableSummaryResponse{value: val, isSet: true}
}

func (v NullableSummaryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSummaryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


