/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.57.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the IntelligenceTaskSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntelligenceTaskSummary{}

// IntelligenceTaskSummary struct for IntelligenceTaskSummary
type IntelligenceTaskSummary struct {
	Id int32 `json:"id"`
	PublicId string `json:"public_id"`
	TaskType string `json:"task_type"`
	Title string `json:"title"`
	Status string `json:"status"`
	PromptId NullableInt32 `json:"prompt_id"`
	PromptText NullableString `json:"prompt_text"`
	WordCount NullableInt32 `json:"word_count"`
	// When the content was last edited by hand; null while the output is as generated
	ManuallyEditedAt NullableTime `json:"manually_edited_at"`
	CreatedAt time.Time `json:"created_at"`
	ProcessedAt NullableTime `json:"processed_at"`
}

type _IntelligenceTaskSummary IntelligenceTaskSummary

// NewIntelligenceTaskSummary instantiates a new IntelligenceTaskSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntelligenceTaskSummary(id int32, publicId string, taskType string, title string, status string, promptId NullableInt32, promptText NullableString, wordCount NullableInt32, manuallyEditedAt NullableTime, createdAt time.Time, processedAt NullableTime) *IntelligenceTaskSummary {
	this := IntelligenceTaskSummary{}
	this.Id = id
	this.PublicId = publicId
	this.TaskType = taskType
	this.Title = title
	this.Status = status
	this.PromptId = promptId
	this.PromptText = promptText
	this.WordCount = wordCount
	this.ManuallyEditedAt = manuallyEditedAt
	this.CreatedAt = createdAt
	this.ProcessedAt = processedAt
	return &this
}

// NewIntelligenceTaskSummaryWithDefaults instantiates a new IntelligenceTaskSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntelligenceTaskSummaryWithDefaults() *IntelligenceTaskSummary {
	this := IntelligenceTaskSummary{}
	return &this
}

// GetId returns the Id field value
func (o *IntelligenceTaskSummary) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *IntelligenceTaskSummary) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *IntelligenceTaskSummary) SetId(v int32) {
	o.Id = v
}

// GetPublicId returns the PublicId field value
func (o *IntelligenceTaskSummary) GetPublicId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicId
}

// GetPublicIdOk returns a tuple with the PublicId field value
// and a boolean to check if the value has been set.
func (o *IntelligenceTaskSummary) GetPublicIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicId, true
}

// SetPublicId sets field value
func (o *IntelligenceTaskSummary) SetPublicId(v string) {
	o.PublicId = v
}

// GetTaskType returns the TaskType field value
func (o *IntelligenceTaskSummary) GetTaskType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskType
}

// GetTaskTypeOk returns a tuple with the TaskType field value
// and a boolean to check if the value has been set.
func (o *IntelligenceTaskSummary) GetTaskTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskType, true
}

// SetTaskType sets field value
func (o *IntelligenceTaskSummary) SetTaskType(v string) {
	o.TaskType = v
}

// GetTitle returns the Title field value
func (o *IntelligenceTaskSummary) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *IntelligenceTaskSummary) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *IntelligenceTaskSummary) SetTitle(v string) {
	o.Title = v
}

// GetStatus returns the Status field value
func (o *IntelligenceTaskSummary) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *IntelligenceTaskSummary) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *IntelligenceTaskSummary) SetStatus(v string) {
	o.Status = v
}

// GetPromptId returns the PromptId field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *IntelligenceTaskSummary) GetPromptId() int32 {
	if o == nil || o.PromptId.Get() == nil {
		var ret int32
		return ret
	}

	return *o.PromptId.Get()
}

// GetPromptIdOk returns a tuple with the PromptId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntelligenceTaskSummary) GetPromptIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PromptId.Get(), o.PromptId.IsSet()
}

// SetPromptId sets field value
func (o *IntelligenceTaskSummary) SetPromptId(v int32) {
	o.PromptId.Set(&v)
}

// GetPromptText returns the PromptText field value
// If the value is explicit nil, the zero value for string will be returned
func (o *IntelligenceTaskSummary) GetPromptText() string {
	if o == nil || o.PromptText.Get() == nil {
		var ret string
		return ret
	}

	return *o.PromptText.Get()
}

// GetPromptTextOk returns a tuple with the PromptText field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntelligenceTaskSummary) GetPromptTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PromptText.Get(), o.PromptText.IsSet()
}

// SetPromptText sets field value
func (o *IntelligenceTaskSummary) SetPromptText(v string) {
	o.PromptText.Set(&v)
}

// GetWordCount returns the WordCount field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *IntelligenceTaskSummary) GetWordCount() int32 {
	if o == nil || o.WordCount.Get() == nil {
		var ret int32
		return ret
	}

	return *o.WordCount.Get()
}

// GetWordCountOk returns a tuple with the WordCount field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntelligenceTaskSummary) GetWordCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.WordCount.Get(), o.WordCount.IsSet()
}

// SetWordCount sets field value
func (o *IntelligenceTaskSummary) SetWordCount(v int32) {
	o.WordCount.Set(&v)
}

// GetManuallyEditedAt returns the ManuallyEditedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *IntelligenceTaskSummary) GetManuallyEditedAt() time.Time {
	if o == nil || o.ManuallyEditedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ManuallyEditedAt.Get()
}

// GetManuallyEditedAtOk returns a tuple with the ManuallyEditedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntelligenceTaskSummary) GetManuallyEditedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ManuallyEditedAt.Get(), o.ManuallyEditedAt.IsSet()
}

// SetManuallyEditedAt sets field value
func (o *IntelligenceTaskSummary) SetManuallyEditedAt(v time.Time) {
	o.ManuallyEditedAt.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *IntelligenceTaskSummary) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *IntelligenceTaskSummary) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *IntelligenceTaskSummary) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetProcessedAt returns the ProcessedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *IntelligenceTaskSummary) GetProcessedAt() time.Time {
	if o == nil || o.ProcessedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ProcessedAt.Get()
}

// GetProcessedAtOk returns a tuple with the ProcessedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntelligenceTaskSummary) GetProcessedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProcessedAt.Get(), o.ProcessedAt.IsSet()
}

// SetProcessedAt sets field value
func (o *IntelligenceTaskSummary) SetProcessedAt(v time.Time) {
	o.ProcessedAt.Set(&v)
}

func (o IntelligenceTaskSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntelligenceTaskSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["public_id"] = o.PublicId
	toSerialize["task_type"] = o.TaskType
	toSerialize["title"] = o.Title
	toSerialize["status"] = o.Status
	toSerialize["prompt_id"] = o.PromptId.Get()
	toSerialize["prompt_text"] = o.PromptText.Get()
	toSerialize["word_count"] = o.WordCount.Get()
	toSerialize["manually_edited_at"] = o.ManuallyEditedAt.Get()
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["processed_at"] = o.ProcessedAt.Get()
	return toSerialize, nil
}

func (o *IntelligenceTaskSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"public_id",
		"task_type",
		"title",
		"status",
		"prompt_id",
		"prompt_text",
		"word_count",
		"manually_edited_at",
		"created_at",
		"processed_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIntelligenceTaskSummary := _IntelligenceTaskSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIntelligenceTaskSummary)

	if err != nil {
		return err
	}

	*o = IntelligenceTaskSummary(varIntelligenceTaskSummary)

	return err
}

type NullableIntelligenceTaskSummary struct {
	value *IntelligenceTaskSummary
	isSet bool
}

func (v NullableIntelligenceTaskSummary) Get() *IntelligenceTaskSummary {
	return v.value
}

func (v *NullableIntelligenceTaskSummary) Set(val *IntelligenceTaskSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableIntelligenceTaskSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableIntelligenceTaskSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntelligenceTaskSummary(val *IntelligenceTaskSummary) *NullableIntelligenceTaskSummary {
	return &NullableIntelligenceTaskSummary{value: val, isSet: true}
}

func (v NullableIntelligenceTaskSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntelligenceTaskSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


