/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.57.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
)

// checks if the GeoAuditComparison type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeoAuditComparison{}

// GeoAuditComparison struct for GeoAuditComparison
type GeoAuditComparison struct {
	ProjectId *int32 `json:"project_id,omitempty"`
	FromRun NullableGeoAuditRun `json:"from_run,omitempty"`
	ToRun NullableGeoAuditRun `json:"to_run,omitempty"`
	Comparable *bool `json:"comparable,omitempty"`
	ScoreDelta NullableFloat32 `json:"score_delta,omitempty"`
	MetricDeltas *map[string]float32 `json:"metric_deltas,omitempty"`
	Counts *map[string]int32 `json:"counts,omitempty"`
	Changes []GeoAuditComparisonChangesInner `json:"changes,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
}

// NewGeoAuditComparison instantiates a new GeoAuditComparison object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeoAuditComparison() *GeoAuditComparison {
	this := GeoAuditComparison{}
	return &this
}

// NewGeoAuditComparisonWithDefaults instantiates a new GeoAuditComparison object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeoAuditComparisonWithDefaults() *GeoAuditComparison {
	this := GeoAuditComparison{}
	return &this
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *GeoAuditComparison) GetProjectId() int32 {
	if o == nil || IsNil(o.ProjectId) {
		var ret int32
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditComparison) GetProjectIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *GeoAuditComparison) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given int32 and assigns it to the ProjectId field.
func (o *GeoAuditComparison) SetProjectId(v int32) {
	o.ProjectId = &v
}

// GetFromRun returns the FromRun field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GeoAuditComparison) GetFromRun() GeoAuditRun {
	if o == nil || IsNil(o.FromRun.Get()) {
		var ret GeoAuditRun
		return ret
	}
	return *o.FromRun.Get()
}

// GetFromRunOk returns a tuple with the FromRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GeoAuditComparison) GetFromRunOk() (*GeoAuditRun, bool) {
	if o == nil {
		return nil, false
	}
	return o.FromRun.Get(), o.FromRun.IsSet()
}

// HasFromRun returns a boolean if a field has been set.
func (o *GeoAuditComparison) HasFromRun() bool {
	if o != nil && o.FromRun.IsSet() {
		return true
	}

	return false
}

// SetFromRun gets a reference to the given NullableGeoAuditRun and assigns it to the FromRun field.
func (o *GeoAuditComparison) SetFromRun(v GeoAuditRun) {
	o.FromRun.Set(&v)
}
// SetFromRunNil sets the value for FromRun to be an explicit nil
func (o *GeoAuditComparison) SetFromRunNil() {
	o.FromRun.Set(nil)
}

// UnsetFromRun ensures that no value is present for FromRun, not even an explicit nil
func (o *GeoAuditComparison) UnsetFromRun() {
	o.FromRun.Unset()
}

// GetToRun returns the ToRun field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GeoAuditComparison) GetToRun() GeoAuditRun {
	if o == nil || IsNil(o.ToRun.Get()) {
		var ret GeoAuditRun
		return ret
	}
	return *o.ToRun.Get()
}

// GetToRunOk returns a tuple with the ToRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GeoAuditComparison) GetToRunOk() (*GeoAuditRun, bool) {
	if o == nil {
		return nil, false
	}
	return o.ToRun.Get(), o.ToRun.IsSet()
}

// HasToRun returns a boolean if a field has been set.
func (o *GeoAuditComparison) HasToRun() bool {
	if o != nil && o.ToRun.IsSet() {
		return true
	}

	return false
}

// SetToRun gets a reference to the given NullableGeoAuditRun and assigns it to the ToRun field.
func (o *GeoAuditComparison) SetToRun(v GeoAuditRun) {
	o.ToRun.Set(&v)
}
// SetToRunNil sets the value for ToRun to be an explicit nil
func (o *GeoAuditComparison) SetToRunNil() {
	o.ToRun.Set(nil)
}

// UnsetToRun ensures that no value is present for ToRun, not even an explicit nil
func (o *GeoAuditComparison) UnsetToRun() {
	o.ToRun.Unset()
}

// GetComparable returns the Comparable field value if set, zero value otherwise.
func (o *GeoAuditComparison) GetComparable() bool {
	if o == nil || IsNil(o.Comparable) {
		var ret bool
		return ret
	}
	return *o.Comparable
}

// GetComparableOk returns a tuple with the Comparable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditComparison) GetComparableOk() (*bool, bool) {
	if o == nil || IsNil(o.Comparable) {
		return nil, false
	}
	return o.Comparable, true
}

// HasComparable returns a boolean if a field has been set.
func (o *GeoAuditComparison) HasComparable() bool {
	if o != nil && !IsNil(o.Comparable) {
		return true
	}

	return false
}

// SetComparable gets a reference to the given bool and assigns it to the Comparable field.
func (o *GeoAuditComparison) SetComparable(v bool) {
	o.Comparable = &v
}

// GetScoreDelta returns the ScoreDelta field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GeoAuditComparison) GetScoreDelta() float32 {
	if o == nil || IsNil(o.ScoreDelta.Get()) {
		var ret float32
		return ret
	}
	return *o.ScoreDelta.Get()
}

// GetScoreDeltaOk returns a tuple with the ScoreDelta field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GeoAuditComparison) GetScoreDeltaOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ScoreDelta.Get(), o.ScoreDelta.IsSet()
}

// HasScoreDelta returns a boolean if a field has been set.
func (o *GeoAuditComparison) HasScoreDelta() bool {
	if o != nil && o.ScoreDelta.IsSet() {
		return true
	}

	return false
}

// SetScoreDelta gets a reference to the given NullableFloat32 and assigns it to the ScoreDelta field.
func (o *GeoAuditComparison) SetScoreDelta(v float32) {
	o.ScoreDelta.Set(&v)
}
// SetScoreDeltaNil sets the value for ScoreDelta to be an explicit nil
func (o *GeoAuditComparison) SetScoreDeltaNil() {
	o.ScoreDelta.Set(nil)
}

// UnsetScoreDelta ensures that no value is present for ScoreDelta, not even an explicit nil
func (o *GeoAuditComparison) UnsetScoreDelta() {
	o.ScoreDelta.Unset()
}

// GetMetricDeltas returns the MetricDeltas field value if set, zero value otherwise.
func (o *GeoAuditComparison) GetMetricDeltas() map[string]float32 {
	if o == nil || IsNil(o.MetricDeltas) {
		var ret map[string]float32
		return ret
	}
	return *o.MetricDeltas
}

// GetMetricDeltasOk returns a tuple with the MetricDeltas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditComparison) GetMetricDeltasOk() (*map[string]float32, bool) {
	if o == nil || IsNil(o.MetricDeltas) {
		return nil, false
	}
	return o.MetricDeltas, true
}

// HasMetricDeltas returns a boolean if a field has been set.
func (o *GeoAuditComparison) HasMetricDeltas() bool {
	if o != nil && !IsNil(o.MetricDeltas) {
		return true
	}

	return false
}

// SetMetricDeltas gets a reference to the given map[string]float32 and assigns it to the MetricDeltas field.
func (o *GeoAuditComparison) SetMetricDeltas(v map[string]float32) {
	o.MetricDeltas = &v
}

// GetCounts returns the Counts field value if set, zero value otherwise.
func (o *GeoAuditComparison) GetCounts() map[string]int32 {
	if o == nil || IsNil(o.Counts) {
		var ret map[string]int32
		return ret
	}
	return *o.Counts
}

// GetCountsOk returns a tuple with the Counts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditComparison) GetCountsOk() (*map[string]int32, bool) {
	if o == nil || IsNil(o.Counts) {
		return nil, false
	}
	return o.Counts, true
}

// HasCounts returns a boolean if a field has been set.
func (o *GeoAuditComparison) HasCounts() bool {
	if o != nil && !IsNil(o.Counts) {
		return true
	}

	return false
}

// SetCounts gets a reference to the given map[string]int32 and assigns it to the Counts field.
func (o *GeoAuditComparison) SetCounts(v map[string]int32) {
	o.Counts = &v
}

// GetChanges returns the Changes field value if set, zero value otherwise.
func (o *GeoAuditComparison) GetChanges() []GeoAuditComparisonChangesInner {
	if o == nil || IsNil(o.Changes) {
		var ret []GeoAuditComparisonChangesInner
		return ret
	}
	return o.Changes
}

// GetChangesOk returns a tuple with the Changes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditComparison) GetChangesOk() ([]GeoAuditComparisonChangesInner, bool) {
	if o == nil || IsNil(o.Changes) {
		return nil, false
	}
	return o.Changes, true
}

// HasChanges returns a boolean if a field has been set.
func (o *GeoAuditComparison) HasChanges() bool {
	if o != nil && !IsNil(o.Changes) {
		return true
	}

	return false
}

// SetChanges gets a reference to the given []GeoAuditComparisonChangesInner and assigns it to the Changes field.
func (o *GeoAuditComparison) SetChanges(v []GeoAuditComparisonChangesInner) {
	o.Changes = v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *GeoAuditComparison) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditComparison) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *GeoAuditComparison) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *GeoAuditComparison) SetRequestId(v string) {
	o.RequestId = &v
}

func (o GeoAuditComparison) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeoAuditComparison) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if o.FromRun.IsSet() {
		toSerialize["from_run"] = o.FromRun.Get()
	}
	if o.ToRun.IsSet() {
		toSerialize["to_run"] = o.ToRun.Get()
	}
	if !IsNil(o.Comparable) {
		toSerialize["comparable"] = o.Comparable
	}
	if o.ScoreDelta.IsSet() {
		toSerialize["score_delta"] = o.ScoreDelta.Get()
	}
	if !IsNil(o.MetricDeltas) {
		toSerialize["metric_deltas"] = o.MetricDeltas
	}
	if !IsNil(o.Counts) {
		toSerialize["counts"] = o.Counts
	}
	if !IsNil(o.Changes) {
		toSerialize["changes"] = o.Changes
	}
	if !IsNil(o.RequestId) {
		toSerialize["request_id"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableGeoAuditComparison struct {
	value *GeoAuditComparison
	isSet bool
}

func (v NullableGeoAuditComparison) Get() *GeoAuditComparison {
	return v.value
}

func (v *NullableGeoAuditComparison) Set(val *GeoAuditComparison) {
	v.value = val
	v.isSet = true
}

func (v NullableGeoAuditComparison) IsSet() bool {
	return v.isSet
}

func (v *NullableGeoAuditComparison) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeoAuditComparison(val *GeoAuditComparison) *NullableGeoAuditComparison {
	return &NullableGeoAuditComparison{value: val, isSet: true}
}

func (v NullableGeoAuditComparison) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeoAuditComparison) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


