/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.56.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CatalogPromptSuggestionsRejectResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogPromptSuggestionsRejectResponse{}

// CatalogPromptSuggestionsRejectResponse struct for CatalogPromptSuggestionsRejectResponse
type CatalogPromptSuggestionsRejectResponse struct {
	ProjectId int32 `json:"project_id"`
	Rejected int32 `json:"rejected"`
	RequestId string `json:"request_id"`
}

type _CatalogPromptSuggestionsRejectResponse CatalogPromptSuggestionsRejectResponse

// NewCatalogPromptSuggestionsRejectResponse instantiates a new CatalogPromptSuggestionsRejectResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogPromptSuggestionsRejectResponse(projectId int32, rejected int32, requestId string) *CatalogPromptSuggestionsRejectResponse {
	this := CatalogPromptSuggestionsRejectResponse{}
	this.ProjectId = projectId
	this.Rejected = rejected
	this.RequestId = requestId
	return &this
}

// NewCatalogPromptSuggestionsRejectResponseWithDefaults instantiates a new CatalogPromptSuggestionsRejectResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogPromptSuggestionsRejectResponseWithDefaults() *CatalogPromptSuggestionsRejectResponse {
	this := CatalogPromptSuggestionsRejectResponse{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *CatalogPromptSuggestionsRejectResponse) GetProjectId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *CatalogPromptSuggestionsRejectResponse) GetProjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *CatalogPromptSuggestionsRejectResponse) SetProjectId(v int32) {
	o.ProjectId = v
}

// GetRejected returns the Rejected field value
func (o *CatalogPromptSuggestionsRejectResponse) GetRejected() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Rejected
}

// GetRejectedOk returns a tuple with the Rejected field value
// and a boolean to check if the value has been set.
func (o *CatalogPromptSuggestionsRejectResponse) GetRejectedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rejected, true
}

// SetRejected sets field value
func (o *CatalogPromptSuggestionsRejectResponse) SetRejected(v int32) {
	o.Rejected = v
}

// GetRequestId returns the RequestId field value
func (o *CatalogPromptSuggestionsRejectResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *CatalogPromptSuggestionsRejectResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *CatalogPromptSuggestionsRejectResponse) SetRequestId(v string) {
	o.RequestId = v
}

func (o CatalogPromptSuggestionsRejectResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogPromptSuggestionsRejectResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["rejected"] = o.Rejected
	toSerialize["request_id"] = o.RequestId
	return toSerialize, nil
}

func (o *CatalogPromptSuggestionsRejectResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"rejected",
		"request_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalogPromptSuggestionsRejectResponse := _CatalogPromptSuggestionsRejectResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCatalogPromptSuggestionsRejectResponse)

	if err != nil {
		return err
	}

	*o = CatalogPromptSuggestionsRejectResponse(varCatalogPromptSuggestionsRejectResponse)

	return err
}

type NullableCatalogPromptSuggestionsRejectResponse struct {
	value *CatalogPromptSuggestionsRejectResponse
	isSet bool
}

func (v NullableCatalogPromptSuggestionsRejectResponse) Get() *CatalogPromptSuggestionsRejectResponse {
	return v.value
}

func (v *NullableCatalogPromptSuggestionsRejectResponse) Set(val *CatalogPromptSuggestionsRejectResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogPromptSuggestionsRejectResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogPromptSuggestionsRejectResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogPromptSuggestionsRejectResponse(val *CatalogPromptSuggestionsRejectResponse) *NullableCatalogPromptSuggestionsRejectResponse {
	return &NullableCatalogPromptSuggestionsRejectResponse{value: val, isSet: true}
}

func (v NullableCatalogPromptSuggestionsRejectResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogPromptSuggestionsRejectResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


