/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.49.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"time"
)

// checks if the SampleWebhookPayloads200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SampleWebhookPayloads200ResponseDataInner{}

// SampleWebhookPayloads200ResponseDataInner struct for SampleWebhookPayloads200ResponseDataInner
type SampleWebhookPayloads200ResponseDataInner struct {
	Event *string `json:"event,omitempty"`
	OccurredAt *time.Time `json:"occurred_at,omitempty"`
	ProjectId *int32 `json:"project_id,omitempty"`
	SubscriptionId *int32 `json:"subscription_id,omitempty"`
	Data map[string]interface{} `json:"data,omitempty"`
}

// NewSampleWebhookPayloads200ResponseDataInner instantiates a new SampleWebhookPayloads200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSampleWebhookPayloads200ResponseDataInner() *SampleWebhookPayloads200ResponseDataInner {
	this := SampleWebhookPayloads200ResponseDataInner{}
	return &this
}

// NewSampleWebhookPayloads200ResponseDataInnerWithDefaults instantiates a new SampleWebhookPayloads200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSampleWebhookPayloads200ResponseDataInnerWithDefaults() *SampleWebhookPayloads200ResponseDataInner {
	this := SampleWebhookPayloads200ResponseDataInner{}
	return &this
}

// GetEvent returns the Event field value if set, zero value otherwise.
func (o *SampleWebhookPayloads200ResponseDataInner) GetEvent() string {
	if o == nil || IsNil(o.Event) {
		var ret string
		return ret
	}
	return *o.Event
}

// GetEventOk returns a tuple with the Event field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SampleWebhookPayloads200ResponseDataInner) GetEventOk() (*string, bool) {
	if o == nil || IsNil(o.Event) {
		return nil, false
	}
	return o.Event, true
}

// HasEvent returns a boolean if a field has been set.
func (o *SampleWebhookPayloads200ResponseDataInner) HasEvent() bool {
	if o != nil && !IsNil(o.Event) {
		return true
	}

	return false
}

// SetEvent gets a reference to the given string and assigns it to the Event field.
func (o *SampleWebhookPayloads200ResponseDataInner) SetEvent(v string) {
	o.Event = &v
}

// GetOccurredAt returns the OccurredAt field value if set, zero value otherwise.
func (o *SampleWebhookPayloads200ResponseDataInner) GetOccurredAt() time.Time {
	if o == nil || IsNil(o.OccurredAt) {
		var ret time.Time
		return ret
	}
	return *o.OccurredAt
}

// GetOccurredAtOk returns a tuple with the OccurredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SampleWebhookPayloads200ResponseDataInner) GetOccurredAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.OccurredAt) {
		return nil, false
	}
	return o.OccurredAt, true
}

// HasOccurredAt returns a boolean if a field has been set.
func (o *SampleWebhookPayloads200ResponseDataInner) HasOccurredAt() bool {
	if o != nil && !IsNil(o.OccurredAt) {
		return true
	}

	return false
}

// SetOccurredAt gets a reference to the given time.Time and assigns it to the OccurredAt field.
func (o *SampleWebhookPayloads200ResponseDataInner) SetOccurredAt(v time.Time) {
	o.OccurredAt = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *SampleWebhookPayloads200ResponseDataInner) GetProjectId() int32 {
	if o == nil || IsNil(o.ProjectId) {
		var ret int32
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SampleWebhookPayloads200ResponseDataInner) GetProjectIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *SampleWebhookPayloads200ResponseDataInner) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given int32 and assigns it to the ProjectId field.
func (o *SampleWebhookPayloads200ResponseDataInner) SetProjectId(v int32) {
	o.ProjectId = &v
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise.
func (o *SampleWebhookPayloads200ResponseDataInner) GetSubscriptionId() int32 {
	if o == nil || IsNil(o.SubscriptionId) {
		var ret int32
		return ret
	}
	return *o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SampleWebhookPayloads200ResponseDataInner) GetSubscriptionIdOk() (*int32, bool) {
	if o == nil || IsNil(o.SubscriptionId) {
		return nil, false
	}
	return o.SubscriptionId, true
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *SampleWebhookPayloads200ResponseDataInner) HasSubscriptionId() bool {
	if o != nil && !IsNil(o.SubscriptionId) {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given int32 and assigns it to the SubscriptionId field.
func (o *SampleWebhookPayloads200ResponseDataInner) SetSubscriptionId(v int32) {
	o.SubscriptionId = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SampleWebhookPayloads200ResponseDataInner) GetData() map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SampleWebhookPayloads200ResponseDataInner) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SampleWebhookPayloads200ResponseDataInner) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *SampleWebhookPayloads200ResponseDataInner) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o SampleWebhookPayloads200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SampleWebhookPayloads200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Event) {
		toSerialize["event"] = o.Event
	}
	if !IsNil(o.OccurredAt) {
		toSerialize["occurred_at"] = o.OccurredAt
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.SubscriptionId) {
		toSerialize["subscription_id"] = o.SubscriptionId
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableSampleWebhookPayloads200ResponseDataInner struct {
	value *SampleWebhookPayloads200ResponseDataInner
	isSet bool
}

func (v NullableSampleWebhookPayloads200ResponseDataInner) Get() *SampleWebhookPayloads200ResponseDataInner {
	return v.value
}

func (v *NullableSampleWebhookPayloads200ResponseDataInner) Set(val *SampleWebhookPayloads200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSampleWebhookPayloads200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSampleWebhookPayloads200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSampleWebhookPayloads200ResponseDataInner(val *SampleWebhookPayloads200ResponseDataInner) *NullableSampleWebhookPayloads200ResponseDataInner {
	return &NullableSampleWebhookPayloads200ResponseDataInner{value: val, isSet: true}
}

func (v NullableSampleWebhookPayloads200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSampleWebhookPayloads200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


