/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.57.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MentionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MentionsResponse{}

// MentionsResponse struct for MentionsResponse
type MentionsResponse struct {
	ProjectId int32 `json:"project_id"`
	Page int32 `json:"page"`
	PerPage int32 `json:"per_page"`
	// Rows matching the filters across every page
	Total int32 `json:"total"`
	RequestId string `json:"request_id"`
	Data []MentionRecord `json:"data"`
}

type _MentionsResponse MentionsResponse

// NewMentionsResponse instantiates a new MentionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMentionsResponse(projectId int32, page int32, perPage int32, total int32, requestId string, data []MentionRecord) *MentionsResponse {
	this := MentionsResponse{}
	this.ProjectId = projectId
	this.Page = page
	this.PerPage = perPage
	this.Total = total
	this.RequestId = requestId
	this.Data = data
	return &this
}

// NewMentionsResponseWithDefaults instantiates a new MentionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMentionsResponseWithDefaults() *MentionsResponse {
	this := MentionsResponse{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *MentionsResponse) GetProjectId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *MentionsResponse) GetProjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *MentionsResponse) SetProjectId(v int32) {
	o.ProjectId = v
}

// GetPage returns the Page field value
func (o *MentionsResponse) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *MentionsResponse) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *MentionsResponse) SetPage(v int32) {
	o.Page = v
}

// GetPerPage returns the PerPage field value
func (o *MentionsResponse) GetPerPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value
// and a boolean to check if the value has been set.
func (o *MentionsResponse) GetPerPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PerPage, true
}

// SetPerPage sets field value
func (o *MentionsResponse) SetPerPage(v int32) {
	o.PerPage = v
}

// GetTotal returns the Total field value
func (o *MentionsResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *MentionsResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *MentionsResponse) SetTotal(v int32) {
	o.Total = v
}

// GetRequestId returns the RequestId field value
func (o *MentionsResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *MentionsResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *MentionsResponse) SetRequestId(v string) {
	o.RequestId = v
}

// GetData returns the Data field value
func (o *MentionsResponse) GetData() []MentionRecord {
	if o == nil {
		var ret []MentionRecord
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *MentionsResponse) GetDataOk() ([]MentionRecord, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *MentionsResponse) SetData(v []MentionRecord) {
	o.Data = v
}

func (o MentionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MentionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["page"] = o.Page
	toSerialize["per_page"] = o.PerPage
	toSerialize["total"] = o.Total
	toSerialize["request_id"] = o.RequestId
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *MentionsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"page",
		"per_page",
		"total",
		"request_id",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMentionsResponse := _MentionsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMentionsResponse)

	if err != nil {
		return err
	}

	*o = MentionsResponse(varMentionsResponse)

	return err
}

type NullableMentionsResponse struct {
	value *MentionsResponse
	isSet bool
}

func (v NullableMentionsResponse) Get() *MentionsResponse {
	return v.value
}

func (v *NullableMentionsResponse) Set(val *MentionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMentionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMentionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMentionsResponse(val *MentionsResponse) *NullableMentionsResponse {
	return &NullableMentionsResponse{value: val, isSet: true}
}

func (v NullableMentionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMentionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


