/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.56.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GeoAuditCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeoAuditCreateRequest{}

// GeoAuditCreateRequest struct for GeoAuditCreateRequest
type GeoAuditCreateRequest struct {
	ProjectId int32 `json:"project_id"`
	// The domain (site-wide types) or page URL to audit
	Target string `json:"target"`
	// One or more audit types; each becomes its own audit and starts its first run
	AuditTypes []string `json:"audit_types"`
	// once (default), weekly or monthly. Weekly and monthly need a type whose checks are tracked and count against the plan limit of recurring audits
	Cadence *string `json:"cadence,omitempty"`
}

type _GeoAuditCreateRequest GeoAuditCreateRequest

// NewGeoAuditCreateRequest instantiates a new GeoAuditCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeoAuditCreateRequest(projectId int32, target string, auditTypes []string) *GeoAuditCreateRequest {
	this := GeoAuditCreateRequest{}
	this.ProjectId = projectId
	this.Target = target
	this.AuditTypes = auditTypes
	return &this
}

// NewGeoAuditCreateRequestWithDefaults instantiates a new GeoAuditCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeoAuditCreateRequestWithDefaults() *GeoAuditCreateRequest {
	this := GeoAuditCreateRequest{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *GeoAuditCreateRequest) GetProjectId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *GeoAuditCreateRequest) GetProjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *GeoAuditCreateRequest) SetProjectId(v int32) {
	o.ProjectId = v
}

// GetTarget returns the Target field value
func (o *GeoAuditCreateRequest) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *GeoAuditCreateRequest) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *GeoAuditCreateRequest) SetTarget(v string) {
	o.Target = v
}

// GetAuditTypes returns the AuditTypes field value
func (o *GeoAuditCreateRequest) GetAuditTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AuditTypes
}

// GetAuditTypesOk returns a tuple with the AuditTypes field value
// and a boolean to check if the value has been set.
func (o *GeoAuditCreateRequest) GetAuditTypesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuditTypes, true
}

// SetAuditTypes sets field value
func (o *GeoAuditCreateRequest) SetAuditTypes(v []string) {
	o.AuditTypes = v
}

// GetCadence returns the Cadence field value if set, zero value otherwise.
func (o *GeoAuditCreateRequest) GetCadence() string {
	if o == nil || IsNil(o.Cadence) {
		var ret string
		return ret
	}
	return *o.Cadence
}

// GetCadenceOk returns a tuple with the Cadence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeoAuditCreateRequest) GetCadenceOk() (*string, bool) {
	if o == nil || IsNil(o.Cadence) {
		return nil, false
	}
	return o.Cadence, true
}

// HasCadence returns a boolean if a field has been set.
func (o *GeoAuditCreateRequest) HasCadence() bool {
	if o != nil && !IsNil(o.Cadence) {
		return true
	}

	return false
}

// SetCadence gets a reference to the given string and assigns it to the Cadence field.
func (o *GeoAuditCreateRequest) SetCadence(v string) {
	o.Cadence = &v
}

func (o GeoAuditCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeoAuditCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["target"] = o.Target
	toSerialize["audit_types"] = o.AuditTypes
	if !IsNil(o.Cadence) {
		toSerialize["cadence"] = o.Cadence
	}
	return toSerialize, nil
}

func (o *GeoAuditCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"target",
		"audit_types",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGeoAuditCreateRequest := _GeoAuditCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGeoAuditCreateRequest)

	if err != nil {
		return err
	}

	*o = GeoAuditCreateRequest(varGeoAuditCreateRequest)

	return err
}

type NullableGeoAuditCreateRequest struct {
	value *GeoAuditCreateRequest
	isSet bool
}

func (v NullableGeoAuditCreateRequest) Get() *GeoAuditCreateRequest {
	return v.value
}

func (v *NullableGeoAuditCreateRequest) Set(val *GeoAuditCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGeoAuditCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGeoAuditCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeoAuditCreateRequest(val *GeoAuditCreateRequest) *NullableGeoAuditCreateRequest {
	return &NullableGeoAuditCreateRequest{value: val, isSet: true}
}

func (v NullableGeoAuditCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeoAuditCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


