/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.48.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PromptsCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromptsCreateRequest{}

// PromptsCreateRequest struct for PromptsCreateRequest
type PromptsCreateRequest struct {
	ProjectId int32 `json:"project_id"`
	Prompts []string `json:"prompts"`
	CountryCode string `json:"country_code"`
	LanguageCode string `json:"language_code"`
}

type _PromptsCreateRequest PromptsCreateRequest

// NewPromptsCreateRequest instantiates a new PromptsCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromptsCreateRequest(projectId int32, prompts []string, countryCode string, languageCode string) *PromptsCreateRequest {
	this := PromptsCreateRequest{}
	this.ProjectId = projectId
	this.Prompts = prompts
	this.CountryCode = countryCode
	this.LanguageCode = languageCode
	return &this
}

// NewPromptsCreateRequestWithDefaults instantiates a new PromptsCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromptsCreateRequestWithDefaults() *PromptsCreateRequest {
	this := PromptsCreateRequest{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *PromptsCreateRequest) GetProjectId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *PromptsCreateRequest) GetProjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *PromptsCreateRequest) SetProjectId(v int32) {
	o.ProjectId = v
}

// GetPrompts returns the Prompts field value
func (o *PromptsCreateRequest) GetPrompts() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Prompts
}

// GetPromptsOk returns a tuple with the Prompts field value
// and a boolean to check if the value has been set.
func (o *PromptsCreateRequest) GetPromptsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Prompts, true
}

// SetPrompts sets field value
func (o *PromptsCreateRequest) SetPrompts(v []string) {
	o.Prompts = v
}

// GetCountryCode returns the CountryCode field value
func (o *PromptsCreateRequest) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *PromptsCreateRequest) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *PromptsCreateRequest) SetCountryCode(v string) {
	o.CountryCode = v
}

// GetLanguageCode returns the LanguageCode field value
func (o *PromptsCreateRequest) GetLanguageCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LanguageCode
}

// GetLanguageCodeOk returns a tuple with the LanguageCode field value
// and a boolean to check if the value has been set.
func (o *PromptsCreateRequest) GetLanguageCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LanguageCode, true
}

// SetLanguageCode sets field value
func (o *PromptsCreateRequest) SetLanguageCode(v string) {
	o.LanguageCode = v
}

func (o PromptsCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromptsCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["prompts"] = o.Prompts
	toSerialize["country_code"] = o.CountryCode
	toSerialize["language_code"] = o.LanguageCode
	return toSerialize, nil
}

func (o *PromptsCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"prompts",
		"country_code",
		"language_code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPromptsCreateRequest := _PromptsCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPromptsCreateRequest)

	if err != nil {
		return err
	}

	*o = PromptsCreateRequest(varPromptsCreateRequest)

	return err
}

type NullablePromptsCreateRequest struct {
	value *PromptsCreateRequest
	isSet bool
}

func (v NullablePromptsCreateRequest) Get() *PromptsCreateRequest {
	return v.value
}

func (v *NullablePromptsCreateRequest) Set(val *PromptsCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePromptsCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePromptsCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromptsCreateRequest(val *PromptsCreateRequest) *NullablePromptsCreateRequest {
	return &NullablePromptsCreateRequest{value: val, isSet: true}
}

func (v NullablePromptsCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromptsCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


