/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.48.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
)

// checks if the ProjectCreateResponseLimits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectCreateResponseLimits{}

// ProjectCreateResponseLimits struct for ProjectCreateResponseLimits
type ProjectCreateResponseLimits struct {
	ProjectsRemaining NullableInt32 `json:"projects_remaining,omitempty"`
	PromptsAvailable NullableInt32 `json:"prompts_available,omitempty"`
	CompetitorsRemaining NullableInt32 `json:"competitors_remaining,omitempty"`
}

// NewProjectCreateResponseLimits instantiates a new ProjectCreateResponseLimits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectCreateResponseLimits() *ProjectCreateResponseLimits {
	this := ProjectCreateResponseLimits{}
	return &this
}

// NewProjectCreateResponseLimitsWithDefaults instantiates a new ProjectCreateResponseLimits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectCreateResponseLimitsWithDefaults() *ProjectCreateResponseLimits {
	this := ProjectCreateResponseLimits{}
	return &this
}

// GetProjectsRemaining returns the ProjectsRemaining field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectCreateResponseLimits) GetProjectsRemaining() int32 {
	if o == nil || IsNil(o.ProjectsRemaining.Get()) {
		var ret int32
		return ret
	}
	return *o.ProjectsRemaining.Get()
}

// GetProjectsRemainingOk returns a tuple with the ProjectsRemaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectCreateResponseLimits) GetProjectsRemainingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectsRemaining.Get(), o.ProjectsRemaining.IsSet()
}

// HasProjectsRemaining returns a boolean if a field has been set.
func (o *ProjectCreateResponseLimits) HasProjectsRemaining() bool {
	if o != nil && o.ProjectsRemaining.IsSet() {
		return true
	}

	return false
}

// SetProjectsRemaining gets a reference to the given NullableInt32 and assigns it to the ProjectsRemaining field.
func (o *ProjectCreateResponseLimits) SetProjectsRemaining(v int32) {
	o.ProjectsRemaining.Set(&v)
}
// SetProjectsRemainingNil sets the value for ProjectsRemaining to be an explicit nil
func (o *ProjectCreateResponseLimits) SetProjectsRemainingNil() {
	o.ProjectsRemaining.Set(nil)
}

// UnsetProjectsRemaining ensures that no value is present for ProjectsRemaining, not even an explicit nil
func (o *ProjectCreateResponseLimits) UnsetProjectsRemaining() {
	o.ProjectsRemaining.Unset()
}

// GetPromptsAvailable returns the PromptsAvailable field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectCreateResponseLimits) GetPromptsAvailable() int32 {
	if o == nil || IsNil(o.PromptsAvailable.Get()) {
		var ret int32
		return ret
	}
	return *o.PromptsAvailable.Get()
}

// GetPromptsAvailableOk returns a tuple with the PromptsAvailable field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectCreateResponseLimits) GetPromptsAvailableOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PromptsAvailable.Get(), o.PromptsAvailable.IsSet()
}

// HasPromptsAvailable returns a boolean if a field has been set.
func (o *ProjectCreateResponseLimits) HasPromptsAvailable() bool {
	if o != nil && o.PromptsAvailable.IsSet() {
		return true
	}

	return false
}

// SetPromptsAvailable gets a reference to the given NullableInt32 and assigns it to the PromptsAvailable field.
func (o *ProjectCreateResponseLimits) SetPromptsAvailable(v int32) {
	o.PromptsAvailable.Set(&v)
}
// SetPromptsAvailableNil sets the value for PromptsAvailable to be an explicit nil
func (o *ProjectCreateResponseLimits) SetPromptsAvailableNil() {
	o.PromptsAvailable.Set(nil)
}

// UnsetPromptsAvailable ensures that no value is present for PromptsAvailable, not even an explicit nil
func (o *ProjectCreateResponseLimits) UnsetPromptsAvailable() {
	o.PromptsAvailable.Unset()
}

// GetCompetitorsRemaining returns the CompetitorsRemaining field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectCreateResponseLimits) GetCompetitorsRemaining() int32 {
	if o == nil || IsNil(o.CompetitorsRemaining.Get()) {
		var ret int32
		return ret
	}
	return *o.CompetitorsRemaining.Get()
}

// GetCompetitorsRemainingOk returns a tuple with the CompetitorsRemaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectCreateResponseLimits) GetCompetitorsRemainingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompetitorsRemaining.Get(), o.CompetitorsRemaining.IsSet()
}

// HasCompetitorsRemaining returns a boolean if a field has been set.
func (o *ProjectCreateResponseLimits) HasCompetitorsRemaining() bool {
	if o != nil && o.CompetitorsRemaining.IsSet() {
		return true
	}

	return false
}

// SetCompetitorsRemaining gets a reference to the given NullableInt32 and assigns it to the CompetitorsRemaining field.
func (o *ProjectCreateResponseLimits) SetCompetitorsRemaining(v int32) {
	o.CompetitorsRemaining.Set(&v)
}
// SetCompetitorsRemainingNil sets the value for CompetitorsRemaining to be an explicit nil
func (o *ProjectCreateResponseLimits) SetCompetitorsRemainingNil() {
	o.CompetitorsRemaining.Set(nil)
}

// UnsetCompetitorsRemaining ensures that no value is present for CompetitorsRemaining, not even an explicit nil
func (o *ProjectCreateResponseLimits) UnsetCompetitorsRemaining() {
	o.CompetitorsRemaining.Unset()
}

func (o ProjectCreateResponseLimits) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectCreateResponseLimits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ProjectsRemaining.IsSet() {
		toSerialize["projects_remaining"] = o.ProjectsRemaining.Get()
	}
	if o.PromptsAvailable.IsSet() {
		toSerialize["prompts_available"] = o.PromptsAvailable.Get()
	}
	if o.CompetitorsRemaining.IsSet() {
		toSerialize["competitors_remaining"] = o.CompetitorsRemaining.Get()
	}
	return toSerialize, nil
}

type NullableProjectCreateResponseLimits struct {
	value *ProjectCreateResponseLimits
	isSet bool
}

func (v NullableProjectCreateResponseLimits) Get() *ProjectCreateResponseLimits {
	return v.value
}

func (v *NullableProjectCreateResponseLimits) Set(val *ProjectCreateResponseLimits) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectCreateResponseLimits) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectCreateResponseLimits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectCreateResponseLimits(val *ProjectCreateResponseLimits) *NullableProjectCreateResponseLimits {
	return &NullableProjectCreateResponseLimits{value: val, isSet: true}
}

func (v NullableProjectCreateResponseLimits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectCreateResponseLimits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


