/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.57.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaginatedEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedEnvelope{}

// PaginatedEnvelope Envelope shared by the paginated listings; each listing adds its own data rows
type PaginatedEnvelope struct {
	ProjectId int32 `json:"project_id"`
	Page int32 `json:"page"`
	PerPage int32 `json:"per_page"`
	// Rows matching the filters across every page
	Total int32 `json:"total"`
	RequestId string `json:"request_id"`
}

type _PaginatedEnvelope PaginatedEnvelope

// NewPaginatedEnvelope instantiates a new PaginatedEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedEnvelope(projectId int32, page int32, perPage int32, total int32, requestId string) *PaginatedEnvelope {
	this := PaginatedEnvelope{}
	this.ProjectId = projectId
	this.Page = page
	this.PerPage = perPage
	this.Total = total
	this.RequestId = requestId
	return &this
}

// NewPaginatedEnvelopeWithDefaults instantiates a new PaginatedEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedEnvelopeWithDefaults() *PaginatedEnvelope {
	this := PaginatedEnvelope{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *PaginatedEnvelope) GetProjectId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *PaginatedEnvelope) GetProjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *PaginatedEnvelope) SetProjectId(v int32) {
	o.ProjectId = v
}

// GetPage returns the Page field value
func (o *PaginatedEnvelope) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *PaginatedEnvelope) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *PaginatedEnvelope) SetPage(v int32) {
	o.Page = v
}

// GetPerPage returns the PerPage field value
func (o *PaginatedEnvelope) GetPerPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value
// and a boolean to check if the value has been set.
func (o *PaginatedEnvelope) GetPerPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PerPage, true
}

// SetPerPage sets field value
func (o *PaginatedEnvelope) SetPerPage(v int32) {
	o.PerPage = v
}

// GetTotal returns the Total field value
func (o *PaginatedEnvelope) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *PaginatedEnvelope) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *PaginatedEnvelope) SetTotal(v int32) {
	o.Total = v
}

// GetRequestId returns the RequestId field value
func (o *PaginatedEnvelope) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *PaginatedEnvelope) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *PaginatedEnvelope) SetRequestId(v string) {
	o.RequestId = v
}

func (o PaginatedEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["page"] = o.Page
	toSerialize["per_page"] = o.PerPage
	toSerialize["total"] = o.Total
	toSerialize["request_id"] = o.RequestId
	return toSerialize, nil
}

func (o *PaginatedEnvelope) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"page",
		"per_page",
		"total",
		"request_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedEnvelope := _PaginatedEnvelope{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedEnvelope)

	if err != nil {
		return err
	}

	*o = PaginatedEnvelope(varPaginatedEnvelope)

	return err
}

type NullablePaginatedEnvelope struct {
	value *PaginatedEnvelope
	isSet bool
}

func (v NullablePaginatedEnvelope) Get() *PaginatedEnvelope {
	return v.value
}

func (v *NullablePaginatedEnvelope) Set(val *PaginatedEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedEnvelope(val *PaginatedEnvelope) *NullablePaginatedEnvelope {
	return &NullablePaginatedEnvelope{value: val, isSet: true}
}

func (v NullablePaginatedEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


