/*
LLM Pulse API

REST API client for LLM Pulse AI visibility analytics.

API version: 1.48.0
Contact: info@llmpulse.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package llmpulse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IntelligenceTaskCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntelligenceTaskCreateRequest{}

// IntelligenceTaskCreateRequest struct for IntelligenceTaskCreateRequest
type IntelligenceTaskCreateRequest struct {
	ProjectId int32 `json:"project_id"`
	TaskType string `json:"task_type"`
	PromptId *int32 `json:"prompt_id,omitempty"`
	CustomTopic *string `json:"custom_topic,omitempty"`
	UserInstructions *string `json:"user_instructions,omitempty"`
	OutputLanguageCode *string `json:"output_language_code,omitempty"`
	ExistingContent *string `json:"existing_content,omitempty"`
	ExistingContentUrl *string `json:"existing_content_url,omitempty"`
}

type _IntelligenceTaskCreateRequest IntelligenceTaskCreateRequest

// NewIntelligenceTaskCreateRequest instantiates a new IntelligenceTaskCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntelligenceTaskCreateRequest(projectId int32, taskType string) *IntelligenceTaskCreateRequest {
	this := IntelligenceTaskCreateRequest{}
	this.ProjectId = projectId
	this.TaskType = taskType
	return &this
}

// NewIntelligenceTaskCreateRequestWithDefaults instantiates a new IntelligenceTaskCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntelligenceTaskCreateRequestWithDefaults() *IntelligenceTaskCreateRequest {
	this := IntelligenceTaskCreateRequest{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *IntelligenceTaskCreateRequest) GetProjectId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *IntelligenceTaskCreateRequest) GetProjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *IntelligenceTaskCreateRequest) SetProjectId(v int32) {
	o.ProjectId = v
}

// GetTaskType returns the TaskType field value
func (o *IntelligenceTaskCreateRequest) GetTaskType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskType
}

// GetTaskTypeOk returns a tuple with the TaskType field value
// and a boolean to check if the value has been set.
func (o *IntelligenceTaskCreateRequest) GetTaskTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskType, true
}

// SetTaskType sets field value
func (o *IntelligenceTaskCreateRequest) SetTaskType(v string) {
	o.TaskType = v
}

// GetPromptId returns the PromptId field value if set, zero value otherwise.
func (o *IntelligenceTaskCreateRequest) GetPromptId() int32 {
	if o == nil || IsNil(o.PromptId) {
		var ret int32
		return ret
	}
	return *o.PromptId
}

// GetPromptIdOk returns a tuple with the PromptId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntelligenceTaskCreateRequest) GetPromptIdOk() (*int32, bool) {
	if o == nil || IsNil(o.PromptId) {
		return nil, false
	}
	return o.PromptId, true
}

// HasPromptId returns a boolean if a field has been set.
func (o *IntelligenceTaskCreateRequest) HasPromptId() bool {
	if o != nil && !IsNil(o.PromptId) {
		return true
	}

	return false
}

// SetPromptId gets a reference to the given int32 and assigns it to the PromptId field.
func (o *IntelligenceTaskCreateRequest) SetPromptId(v int32) {
	o.PromptId = &v
}

// GetCustomTopic returns the CustomTopic field value if set, zero value otherwise.
func (o *IntelligenceTaskCreateRequest) GetCustomTopic() string {
	if o == nil || IsNil(o.CustomTopic) {
		var ret string
		return ret
	}
	return *o.CustomTopic
}

// GetCustomTopicOk returns a tuple with the CustomTopic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntelligenceTaskCreateRequest) GetCustomTopicOk() (*string, bool) {
	if o == nil || IsNil(o.CustomTopic) {
		return nil, false
	}
	return o.CustomTopic, true
}

// HasCustomTopic returns a boolean if a field has been set.
func (o *IntelligenceTaskCreateRequest) HasCustomTopic() bool {
	if o != nil && !IsNil(o.CustomTopic) {
		return true
	}

	return false
}

// SetCustomTopic gets a reference to the given string and assigns it to the CustomTopic field.
func (o *IntelligenceTaskCreateRequest) SetCustomTopic(v string) {
	o.CustomTopic = &v
}

// GetUserInstructions returns the UserInstructions field value if set, zero value otherwise.
func (o *IntelligenceTaskCreateRequest) GetUserInstructions() string {
	if o == nil || IsNil(o.UserInstructions) {
		var ret string
		return ret
	}
	return *o.UserInstructions
}

// GetUserInstructionsOk returns a tuple with the UserInstructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntelligenceTaskCreateRequest) GetUserInstructionsOk() (*string, bool) {
	if o == nil || IsNil(o.UserInstructions) {
		return nil, false
	}
	return o.UserInstructions, true
}

// HasUserInstructions returns a boolean if a field has been set.
func (o *IntelligenceTaskCreateRequest) HasUserInstructions() bool {
	if o != nil && !IsNil(o.UserInstructions) {
		return true
	}

	return false
}

// SetUserInstructions gets a reference to the given string and assigns it to the UserInstructions field.
func (o *IntelligenceTaskCreateRequest) SetUserInstructions(v string) {
	o.UserInstructions = &v
}

// GetOutputLanguageCode returns the OutputLanguageCode field value if set, zero value otherwise.
func (o *IntelligenceTaskCreateRequest) GetOutputLanguageCode() string {
	if o == nil || IsNil(o.OutputLanguageCode) {
		var ret string
		return ret
	}
	return *o.OutputLanguageCode
}

// GetOutputLanguageCodeOk returns a tuple with the OutputLanguageCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntelligenceTaskCreateRequest) GetOutputLanguageCodeOk() (*string, bool) {
	if o == nil || IsNil(o.OutputLanguageCode) {
		return nil, false
	}
	return o.OutputLanguageCode, true
}

// HasOutputLanguageCode returns a boolean if a field has been set.
func (o *IntelligenceTaskCreateRequest) HasOutputLanguageCode() bool {
	if o != nil && !IsNil(o.OutputLanguageCode) {
		return true
	}

	return false
}

// SetOutputLanguageCode gets a reference to the given string and assigns it to the OutputLanguageCode field.
func (o *IntelligenceTaskCreateRequest) SetOutputLanguageCode(v string) {
	o.OutputLanguageCode = &v
}

// GetExistingContent returns the ExistingContent field value if set, zero value otherwise.
func (o *IntelligenceTaskCreateRequest) GetExistingContent() string {
	if o == nil || IsNil(o.ExistingContent) {
		var ret string
		return ret
	}
	return *o.ExistingContent
}

// GetExistingContentOk returns a tuple with the ExistingContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntelligenceTaskCreateRequest) GetExistingContentOk() (*string, bool) {
	if o == nil || IsNil(o.ExistingContent) {
		return nil, false
	}
	return o.ExistingContent, true
}

// HasExistingContent returns a boolean if a field has been set.
func (o *IntelligenceTaskCreateRequest) HasExistingContent() bool {
	if o != nil && !IsNil(o.ExistingContent) {
		return true
	}

	return false
}

// SetExistingContent gets a reference to the given string and assigns it to the ExistingContent field.
func (o *IntelligenceTaskCreateRequest) SetExistingContent(v string) {
	o.ExistingContent = &v
}

// GetExistingContentUrl returns the ExistingContentUrl field value if set, zero value otherwise.
func (o *IntelligenceTaskCreateRequest) GetExistingContentUrl() string {
	if o == nil || IsNil(o.ExistingContentUrl) {
		var ret string
		return ret
	}
	return *o.ExistingContentUrl
}

// GetExistingContentUrlOk returns a tuple with the ExistingContentUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntelligenceTaskCreateRequest) GetExistingContentUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ExistingContentUrl) {
		return nil, false
	}
	return o.ExistingContentUrl, true
}

// HasExistingContentUrl returns a boolean if a field has been set.
func (o *IntelligenceTaskCreateRequest) HasExistingContentUrl() bool {
	if o != nil && !IsNil(o.ExistingContentUrl) {
		return true
	}

	return false
}

// SetExistingContentUrl gets a reference to the given string and assigns it to the ExistingContentUrl field.
func (o *IntelligenceTaskCreateRequest) SetExistingContentUrl(v string) {
	o.ExistingContentUrl = &v
}

func (o IntelligenceTaskCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntelligenceTaskCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["task_type"] = o.TaskType
	if !IsNil(o.PromptId) {
		toSerialize["prompt_id"] = o.PromptId
	}
	if !IsNil(o.CustomTopic) {
		toSerialize["custom_topic"] = o.CustomTopic
	}
	if !IsNil(o.UserInstructions) {
		toSerialize["user_instructions"] = o.UserInstructions
	}
	if !IsNil(o.OutputLanguageCode) {
		toSerialize["output_language_code"] = o.OutputLanguageCode
	}
	if !IsNil(o.ExistingContent) {
		toSerialize["existing_content"] = o.ExistingContent
	}
	if !IsNil(o.ExistingContentUrl) {
		toSerialize["existing_content_url"] = o.ExistingContentUrl
	}
	return toSerialize, nil
}

func (o *IntelligenceTaskCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"task_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIntelligenceTaskCreateRequest := _IntelligenceTaskCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIntelligenceTaskCreateRequest)

	if err != nil {
		return err
	}

	*o = IntelligenceTaskCreateRequest(varIntelligenceTaskCreateRequest)

	return err
}

type NullableIntelligenceTaskCreateRequest struct {
	value *IntelligenceTaskCreateRequest
	isSet bool
}

func (v NullableIntelligenceTaskCreateRequest) Get() *IntelligenceTaskCreateRequest {
	return v.value
}

func (v *NullableIntelligenceTaskCreateRequest) Set(val *IntelligenceTaskCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIntelligenceTaskCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIntelligenceTaskCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntelligenceTaskCreateRequest(val *IntelligenceTaskCreateRequest) *NullableIntelligenceTaskCreateRequest {
	return &NullableIntelligenceTaskCreateRequest{value: val, isSet: true}
}

func (v NullableIntelligenceTaskCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntelligenceTaskCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


